from collections import namedtuple

from artiq.experiment import *


Variable = namedtuple("Variable", ["name", "value", "value_type", "kwargs", "group"])


NODE2_VARIABLES = (
    Variable('require_atom_loading_to_advance_Node2', False, BooleanValue, {}, 'general'),
    Variable('require_atom_loading_to_advance_in_single_photon_exp_Node2', True, BooleanValue, {}, 'single photon experiment'),
    Variable('n_excitation_attempts_Node2', 4, NumberValue, {'type': 'int', 'ndecimals': 0, 'step': 1, 'scale': 1}, 'single photon experiment'),
    Variable('max_excitation_cycles_Node2', 2000, NumberValue, {'type': 'int', 'ndecimals': 0, 'step': 1, 'scale': 1}, 'single photon experiment'),
    Variable('atom_check_every_n_Node2', 30, NumberValue, {'type': 'int', 'ndecimals': 0, 'step': 1, 'scale': 1}, 'single photon experiment'),
    Variable('recool_every_n_OP_Node2', 1, NumberValue, {'type': 'int', 'ndecimals': 0, 'step': 1, 'scale': 1}, 'single photon experiment'),
    Variable('record_every_shot_Node2', True, BooleanValue, {}, 'single photon experiment'),
    Variable('dummy_variable_Node2', 0.0, NumberValue, {'type': 'float'}, 'debugging'),
    Variable('monitor_magnetometer_in_end_measurement_Node2', False, BooleanValue, {}, 'debugging'),
    Variable('f_FORT_Node2', 240000000.0, NumberValue, {'type': 'float', 'unit': 'MHz'}, 'FORT AOM'),
    Variable('p_FORT_loading_Node2', -10.968613745406444, NumberValue, {'type': 'float', 'unit': 'dBm', 'scale': 1, 'ndecimals': 1}, 'FORT AOM'),
    Variable('p_FORT_holding_Node2', 0.65, NumberValue, {'type': 'float', 'unit': '(fractional)', 'scale': 1, 'ndecimals': 2}, 'FORT AOM - outdated'),
    Variable('p_FORT_RO_Node2', 0.9, NumberValue, {'type': 'float', 'unit': '(fractional)', 'scale': 1, 'ndecimals': 1}, 'FORT AOM - outdated'),
    Variable('p_FORT_PGC_Node2', 0.9, NumberValue, {'type': 'float', 'unit': '(fractional)', 'scale': 1, 'ndecimals': 2}, 'FORT AOM - outdated'),
    Variable('p_FORT_blowaway_Node2', 0.7, NumberValue, {'type': 'float', 'unit': '(fractional)', 'scale': 1, 'ndecimals': 2}, 'FORT AOM - outdated'),
    Variable('p_FORT_OP_Node2', 0.8, NumberValue, {'type': 'float', 'unit': '(fractional)', 'scale': 1, 'ndecimals': 2}, 'FORT AOM - outdated'),
    Variable('f_cooling_DP_MOT_Node2', 115000000.0, NumberValue, {'type': 'float', 'unit': 'MHz'}, 'Cooling double pass AOM'),
    Variable('f_cooling_DP_RO_Node2', 130000000.0, NumberValue, {'type': 'float', 'unit': 'MHz'}, 'Cooling double pass AOM'),
    Variable('f_cooling_DP_PGC_Node2', 130000000.0, NumberValue, {'type': 'float', 'unit': 'MHz'}, 'Cooling double pass AOM'),
    Variable('f_cooling_DP_PGC_optimization_Node2', 130000000.0, NumberValue, {'type': 'float', 'unit': 'MHz'}, 'Cooling double pass AOM'),
    Variable('f_cooling_DP_resonant_2_to_3_Node2', 104250000.0, NumberValue, {'type': 'float', 'unit': 'MHz'}, 'Cooling double pass AOM'),
    Variable('f_cooling_DP_blowaway_Node2', 112000000.0, NumberValue, {'type': 'float', 'unit': 'MHz'}, 'Cooling double pass AOM'),
    Variable('p_cooling_DP_MOT_Node2', -4.0, NumberValue, {'type': 'float', 'unit': 'dBm', 'scale': 1, 'ndecimals': 1}, 'Cooling double pass AOM'),
    Variable('p_cooling_DP_RO_Node2', 0.8, NumberValue, {'type': 'float', 'unit': '(fractional 0.0 to 1.0)', 'scale': 1, 'ndecimals': 2}, 'Cooling double pass AOM'),
    Variable('p_cooling_DP_PGC_Node2', 0.7999999999999999, NumberValue, {'type': 'float', 'unit': '(fractional 0.0 to 1.0)', 'scale': 1, 'ndecimals': 2}, 'Cooling double pass AOM'),
    Variable('p_cooling_DP_PGC_optimization_Node2', 0.9, NumberValue, {'type': 'float', 'unit': '(fractional 0.0 to 1.0)', 'scale': 1, 'ndecimals': 2}, 'Cooling double pass AOM'),
    Variable('f_D1_pumping_DP_Node2', 150500000.0, NumberValue, {'type': 'float', 'unit': 'MHz', 'ndecimals': 3}, 'OP and excitation AOMs'),
    Variable('p_D1_pumping_DP_Node2', -20.0, NumberValue, {'type': 'float', 'unit': 'dBm', 'scale': 1, 'ndecimals': 1}, 'OP and excitation AOMs'),
    Variable('f_excitation_Node2', 150500000.0, NumberValue, {'type': 'float', 'unit': 'MHz'}, 'OP and excitation AOMs'),
    Variable('p_excitation_Node2', -5.0, NumberValue, {'type': 'float', 'unit': 'dBm', 'scale': 1, 'ndecimals': 1}, 'OP and excitation AOMs'),
    Variable('max_pumping_cycles_Node2', 10, NumberValue, {'type': 'int', 'ndecimals': 0, 'step': 1, 'scale': 1}, 'Node2 GRIN1 and GRIN2'),
    Variable('f_GRIN1_D1_pumping_Node2', 150500000.0, NumberValue, {'type': 'float', 'unit': 'MHz'}, 'Node2 GRIN1 and GRIN2'),
    Variable('p_GRIN1_D1_pumping_Node2', -8.0, NumberValue, {'type': 'float', 'unit': 'dBm', 'scale': 1, 'ndecimals': 1}, 'Node2 GRIN1 and GRIN2'),
    Variable('f_GRIN2_D1_pumping_Node2', 150600000.0, NumberValue, {'type': 'float', 'unit': 'MHz'}, 'Node2 GRIN1 and GRIN2'),
    Variable('p_GRIN2_D1_pumping_Node2', -150.0, NumberValue, {'type': 'float', 'unit': 'dBm', 'scale': 1, 'ndecimals': 1}, 'Node2 GRIN1 and GRIN2'),
    Variable('f_GRIN1_excitation_Node2', 150500000.0, NumberValue, {'type': 'float', 'unit': 'MHz'}, 'Node2 GRIN1 and GRIN2'),
    Variable('p_GRIN1_excitation_Node2', -150.0, NumberValue, {'type': 'float', 'unit': 'dBm', 'scale': 1, 'ndecimals': 1}, 'Node2 GRIN1 and GRIN2'),
    Variable('f_GRIN2_excitation_Node2', 150500000.0, NumberValue, {'type': 'float', 'unit': 'MHz'}, 'Node2 GRIN1 and GRIN2'),
    Variable('p_GRIN2_excitation_Node2', -6.0, NumberValue, {'type': 'float', 'unit': 'dBm', 'scale': 1, 'ndecimals': 1}, 'Node2 GRIN1 and GRIN2'),
    Variable('AOM_A1_freq_Node2', 78480000.0, NumberValue, {'type': 'float', 'unit': 'MHz', 'ndecimals': 3}, 'Fiber AOMs'),
    Variable('p_AOM_A1_Node2', -17.861801542626836, NumberValue, {'type': 'float', 'unit': 'dBm', 'scale': 1, 'ndecimals': 1}, 'Fiber AOMs'),
    Variable('p_AOM_A1_optimization_Node2', -13.0, NumberValue, {'type': 'float', 'unit': 'dBm', 'scale': 1, 'ndecimals': 1}, 'Fiber AOMs'),
    Variable('AOM_A2_freq_Node2', 78490000.0, NumberValue, {'type': 'float', 'unit': 'MHz', 'ndecimals': 3}, 'Fiber AOMs'),
    Variable('p_AOM_A2_Node2', -10.875288704533306, NumberValue, {'type': 'float', 'unit': 'dBm', 'scale': 1, 'ndecimals': 1}, 'Fiber AOMs'),
    Variable('p_AOM_A2_optimization_Node2', -13.0, NumberValue, {'type': 'float', 'unit': 'dBm', 'scale': 1, 'ndecimals': 1}, 'Fiber AOMs'),
    Variable('AOM_A3_freq_Node2', 78500000.0, NumberValue, {'type': 'float', 'unit': 'MHz', 'ndecimals': 3}, 'Fiber AOMs'),
    Variable('p_AOM_A3_Node2', -15.55073229549838, NumberValue, {'type': 'float', 'unit': 'dBm', 'scale': 1, 'ndecimals': 1}, 'Fiber AOMs'),
    Variable('p_AOM_A3_optimization_Node2', -13.0, NumberValue, {'type': 'float', 'unit': 'dBm', 'scale': 1, 'ndecimals': 1}, 'Fiber AOMs'),
    Variable('AOM_A4_freq_Node2', 78510000.0, NumberValue, {'type': 'float', 'unit': 'MHz', 'ndecimals': 3}, 'Fiber AOMs'),
    Variable('p_AOM_A4_Node2', -11.657436449350849, NumberValue, {'type': 'float', 'unit': 'dBm', 'scale': 1, 'ndecimals': 1}, 'Fiber AOMs'),
    Variable('p_AOM_A4_optimization_Node2', -13.0, NumberValue, {'type': 'float', 'unit': 'dBm', 'scale': 1, 'ndecimals': 1}, 'Fiber AOMs'),
    Variable('AOM_A5_freq_Node2', 78520000.0, NumberValue, {'type': 'float', 'unit': 'MHz', 'ndecimals': 3}, 'Fiber AOMs'),
    Variable('p_AOM_A5_Node2', -22.72913127060436, NumberValue, {'type': 'float', 'unit': 'dBm', 'scale': 1, 'ndecimals': 1}, 'Fiber AOMs'),
    Variable('p_AOM_A5_optimization_Node2', -13.0, NumberValue, {'type': 'float', 'unit': 'dBm', 'scale': 1, 'ndecimals': 1}, 'Fiber AOMs'),
    Variable('AOM_A6_freq_Node2', 78530000.0, NumberValue, {'type': 'float', 'unit': 'MHz', 'ndecimals': 3}, 'Fiber AOMs'),
    Variable('p_AOM_A6_Node2', -21.359881707200906, NumberValue, {'type': 'float', 'unit': 'dBm', 'scale': 1, 'ndecimals': 1}, 'Fiber AOMs'),
    Variable('p_AOM_A6_optimization_Node2', -13.0, NumberValue, {'type': 'float', 'unit': 'dBm', 'scale': 1, 'ndecimals': 1}, 'Fiber AOMs'),
    Variable('f_microwaves_dds_Node2', 334662000.0, NumberValue, {'type': 'float', 'unit': 'MHz', 'ndecimals': 7}, 'Microwaves'),
    Variable('f_microwaves_detuning_Node2', 250000.0, NumberValue, {'type': 'float', 'unit': 'MHz', 'ndecimals': 7}, 'Microwaves'),
    Variable('p_microwaves_Node2', -1.0, NumberValue, {'type': 'float', 'unit': 'dBm', 'scale': 1, 'ndecimals': 1}, 'Microwaves'),
    Variable('f_microwaves_00_dds_Node2', 334672000.0, NumberValue, {'type': 'float', 'unit': 'MHz', 'ndecimals': 7}, 'Microwaves'),
    Variable('f_microwaves_01_dds_Node2', 336994000.0, NumberValue, {'type': 'float', 'unit': 'MHz', 'ndecimals': 7}, 'Microwaves'),
    Variable('f_microwaves_11_dds_Node2', 339323000.0, NumberValue, {'type': 'float', 'unit': 'MHz', 'ndecimals': 7}, 'Microwaves'),
    Variable('f_microwaves_m10_dds_Node2', 332329000.0, NumberValue, {'type': 'float', 'unit': 'MHz', 'ndecimals': 7}, 'Microwaves'),
    Variable('f_microwaves_m11_dds_Node2', 331939000.0, NumberValue, {'type': 'float', 'unit': 'MHz', 'ndecimals': 7}, 'Microwaves'),
    Variable('f_MW_RF_dds_Node2', 2738000.0, NumberValue, {'type': 'float', 'unit': 'MHz', 'ndecimals': 7}, 'Microwaves'),
    Variable('p_MW_RF_dds_Node2', -3.0, NumberValue, {'type': 'float', 'unit': 'dBm', 'scale': 1, 'ndecimals': 1}, 'Microwaves'),
    Variable('t_microwave_pulse_Node2', 7.2e-06, NumberValue, {'type': 'float', 'unit': 'us'}, 'Microwaves'),
    Variable('t_microwave_00_pulse_Node2', 7.6e-06, NumberValue, {'type': 'float', 'unit': 'us'}, 'Microwaves'),
    Variable('t_microwave_01_pulse_Node2', 5.4e-06, NumberValue, {'type': 'float', 'unit': 'us'}, 'Microwaves'),
    Variable('t_microwave_11_pulse_Node2', 9.1e-06, NumberValue, {'type': 'float', 'unit': 'us'}, 'Microwaves'),
    Variable('t_microwave_m10_pulse_Node2', 9.4e-06, NumberValue, {'type': 'float', 'unit': 'us'}, 'Microwaves'),
    Variable('t_microwave_m1m1_pulse_Node2', 6e-06, NumberValue, {'type': 'float', 'unit': 'us'}, 'Microwaves'),
    Variable('t_MW_RF_pulse_Node2', 6.96e-05, NumberValue, {'type': 'float', 'unit': 'us'}, 'Microwaves'),
    Variable('t_MW_00_ramp_Node2', 2e-06, NumberValue, {'type': 'float', 'unit': 'us'}, 'Microwaves'),
    Variable('t_MW_01_ramp_Node2', 4e-06, NumberValue, {'type': 'float', 'unit': 'us'}, 'Microwaves'),
    Variable('t_MW_11_ramp_Node2', 2e-06, NumberValue, {'type': 'float', 'unit': 'us'}, 'Microwaves'),
    Variable('AZ_bottom_volts_MOT_Node2', 4.802, NumberValue, {'type': 'float', 'unit': 'V', 'ndecimals': 3}, 'MOT coil settings'),
    Variable('AZ_top_volts_MOT_Node2', 6.014, NumberValue, {'type': 'float', 'unit': 'V', 'ndecimals': 3}, 'MOT coil settings'),
    Variable('AX_volts_MOT_Node2', 0.194, NumberValue, {'type': 'float', 'unit': 'V', 'ndecimals': 3}, 'MOT coil settings'),
    Variable('AY_volts_MOT_Node2', -1.426, NumberValue, {'type': 'float', 'unit': 'V', 'ndecimals': 3}, 'MOT coil settings'),
    Variable('AZ_bottom_volts_PGC_Node2', -0.205, NumberValue, {'type': 'float', 'unit': 'V', 'ndecimals': 3}, 'MOT coil settings'),
    Variable('AX_volts_PGC_Node2', -0.3, NumberValue, {'type': 'float', 'unit': 'V', 'ndecimals': 3}, 'MOT coil settings'),
    Variable('AY_volts_PGC_Node2', -0.9, NumberValue, {'type': 'float', 'unit': 'V', 'ndecimals': 3}, 'MOT coil settings'),
    Variable('AZ_bottom_volts_PGC_optimization_Node2', -0.196, NumberValue, {'type': 'float', 'unit': 'V', 'ndecimals': 3}, 'MOT coil settings'),
    Variable('AX_volts_PGC_optimization_Node2', 0.115, NumberValue, {'type': 'float', 'unit': 'V', 'ndecimals': 3}, 'MOT coil settings'),
    Variable('AY_volts_PGC_optimization_Node2', -0.291, NumberValue, {'type': 'float', 'unit': 'V', 'ndecimals': 3}, 'MOT coil settings'),
    Variable('AZ_bottom_volts_OP_Node2', -0.28, NumberValue, {'type': 'float', 'unit': 'V', 'ndecimals': 3}, 'Science coil settings'),
    Variable('AX_volts_OP_Node2', -0.5, NumberValue, {'type': 'float', 'unit': 'V', 'ndecimals': 3}, 'Science coil settings'),
    Variable('AY_volts_OP_Node2', 7.03, NumberValue, {'type': 'float', 'unit': 'V', 'ndecimals': 3}, 'Science coil settings'),
    Variable('AZ_bottom_volts_blowaway_Node2', -0.4, NumberValue, {'type': 'float', 'unit': 'V', 'ndecimals': 3}, 'Science coil settings'),
    Variable('AX_volts_blowaway_Node2', 0.0, NumberValue, {'type': 'float', 'unit': 'V', 'ndecimals': 3}, 'Science coil settings'),
    Variable('AY_volts_blowaway_Node2', 0.0, NumberValue, {'type': 'float', 'unit': 'V', 'ndecimals': 3}, 'Science coil settings'),
    Variable('AZ_bottom_volts_microwave_Node2', 0.0, NumberValue, {'type': 'float', 'unit': 'V', 'ndecimals': 3}, 'Science coil settings'),
    Variable('AX_volts_microwave_Node2', 0.0, NumberValue, {'type': 'float', 'unit': 'V', 'ndecimals': 3}, 'Science coil settings'),
    Variable('AY_volts_microwave_Node2', 0.0, NumberValue, {'type': 'float', 'unit': 'V', 'ndecimals': 3}, 'Science coil settings'),
    Variable('t_MOT_loading_Node2', 0.5, NumberValue, {'type': 'float', 'unit': 'ms'}, 'Timing'),
    Variable('t_FORT_loading_Node2', 0.1, NumberValue, {'type': 'float', 'unit': 'ms'}, 'Timing'),
    Variable('t_FORT_drop_Node2', 0.0, NumberValue, {'type': 'float', 'unit': 'us'}, 'Timing'),
    Variable('t_FORT_modulation_Node2', 0.0, NumberValue, {'type': 'float', 'unit': 'ms'}, 'Timing'),
    Variable('t_FORT_ramp_Node2', 0.001, NumberValue, {'type': 'float', 'unit': 'ms'}, 'Timing'),
    Variable('t_FORT_step_Node2', 9.999999999999999e-06, NumberValue, {'type': 'float', 'unit': 'ms'}, 'Timing'),
    Variable('t_SPCM_exposure_Node2', 0.01, NumberValue, {'type': 'float', 'unit': 'ms'}, 'Timing'),
    Variable('t_atom_check_time_Node2', 0.01, NumberValue, {'type': 'float', 'unit': 'ms'}, 'Timing'),
    Variable('t_SPCM_first_shot_Node2', 0.01, NumberValue, {'type': 'float', 'unit': 'ms'}, 'Timing'),
    Variable('t_SPCM_second_shot_Node2', 0.01, NumberValue, {'type': 'float', 'unit': 'ms'}, 'Timing'),
    Variable('t_SPCM_test_shot_Node2', 0.01, NumberValue, {'type': 'float', 'unit': 'ms'}, 'Timing'),
    Variable('t_SPCM_recool_and_shot_Node2', 0.01, NumberValue, {'type': 'float', 'unit': 'ms'}, 'Timing'),
    Variable('t_delay_between_shots_Node2', 0.0, NumberValue, {'type': 'float', 'unit': 'ms'}, 'Timing'),
    Variable('t_PGC_after_loading_Node2', 0.001, NumberValue, {'type': 'float', 'unit': 'ms'}, 'Timing'),
    Variable('t_recooling_after_first_shot_Node2', 0.001, NumberValue, {'type': 'float', 'unit': 'us'}, 'Timing'),
    Variable('t_MOT_dissipation_Node2', 0.05, NumberValue, {'type': 'float', 'unit': 'ms'}, 'Timing'),
    Variable('t_blowaway_Node2', 2.9999999999999997e-05, NumberValue, {'type': 'float', 'unit': 'us'}, 'Timing'),
    Variable('t_pumping_Node2', 3e-05, NumberValue, {'type': 'float', 'unit': 'us'}, 'Timing'),
    Variable('t_depumping_Node2', 2e-06, NumberValue, {'type': 'float', 'unit': 'us'}, 'Timing'),
    Variable('t_exp_trigger_Node2', 0.001, NumberValue, {'type': 'float', 'unit': 'ms'}, 'Timing'),
    Variable('t_OP_chop_period_Node2', 1e-06, NumberValue, {'type': 'float', 'unit': 'us'}, 'Timing'),
    Variable('t_OP_chop_offset_Node2', 5e-07, NumberValue, {'type': 'float', 'unit': 'us'}, 'Timing'),
    Variable('t_BA_chop_period_Node2', 1e-06, NumberValue, {'type': 'float', 'unit': 'us'}, 'Timing'),
    Variable('duty_cycle_OP_Node2', 0.35, NumberValue, {'type': 'float', 'unit': '(fractional 0.0 to 1.0)', 'scale': 1, 'ndecimals': 2}, 'Timing'),
    Variable('duty_cycle_FORT_Node2', 0.65, NumberValue, {'type': 'float', 'unit': '(fractional 0.0 to 1.0)', 'scale': 1, 'ndecimals': 2}, 'Timing'),
    Variable('chop_RO_FORT_off_Node2', 5e-07, NumberValue, {'type': 'float', 'unit': 'us'}, 'Timing'),
    Variable('chop_RO_pulse_length_Node2', 4e-07, NumberValue, {'type': 'float', 'unit': 'us'}, 'Timing'),
    Variable('chop_RO_pulse_offset_Node2', 2e-07, NumberValue, {'type': 'float', 'unit': 'us'}, 'Timing'),
    Variable('chop_RO_gate_length_Node2', 5e-07, NumberValue, {'type': 'float', 'unit': 'us'}, 'Timing'),
    Variable('chop_RO_gate_offset_Node2', 1e-07, NumberValue, {'type': 'float', 'unit': 'us'}, 'Timing'),
    Variable('t_recooling_Node2', 0.0006, NumberValue, {'type': 'float', 'unit': 'ms'}, 'Timing'),
    Variable('t_photon_collection_time_Node2', 2.0000000000000002e-07, NumberValue, {'type': 'float', 'unit': 'ns'}, 'Timing'),
    Variable('gate_start_offset_mu_Node2', 500, NumberValue, {'type': 'int', 'ndecimals': 0, 'scale': 1, 'step': 1}, 'Timing'),
    Variable('t_excitation_pulse_Node2', 3.0000000000000004e-08, NumberValue, {'type': 'float', 'unit': 'ns'}, 'Timing'),
    Variable('t_excitation_offset_mu_Node2', -230, NumberValue, {'type': 'int', 'ndecimals': 0, 'scale': 1, 'step': 1}, 'Timing'),
    Variable('t_start_MW_mapping_mu_Node2', 10000, NumberValue, {'type': 'int', 'ndecimals': 0, 'scale': 1, 'step': 1}, 'Timing'),
    Variable('no_first_shot_Node2', False, BooleanValue, {}, 'Booleans'),
    Variable('do_PGC_after_loading_Node2', True, BooleanValue, {}, 'Booleans'),
    Variable('pumping_light_off_Node2', False, BooleanValue, {}, 'Booleans'),
    Variable('blowaway_light_off_Node2', False, BooleanValue, {}, 'Booleans'),
    Variable('FORT_on_at_MOT_start_Node2', True, BooleanValue, {}, 'Booleans'),
    Variable('D1_off_in_OP_phase_Node2', False, BooleanValue, {}, 'Booleans'),
    Variable('D1_off_in_depump_phase_Node2', False, BooleanValue, {}, 'Booleans'),
    Variable('require_D1_lock_to_advance_Node2', False, BooleanValue, {}, 'Booleans'),
    Variable('use_chopped_readout_Node2', False, BooleanValue, {}, 'Booleans'),
    Variable('chopped_RO_light_off_Node2', False, BooleanValue, {}, 'Booleans'),
    Variable('verify_OP_in_photon_experiment_Node2', False, BooleanValue, {}, 'Booleans'),
    Variable('monitors_for_atom_loading_Node2', False, BooleanValue, {}, 'Booleans'),
    Variable('PGC_and_RO_with_on_chip_beams_Node2', True, BooleanValue, {}, 'Booleans'),
    Variable('tune_shims_when_loading_is_bad_Node2', False, BooleanValue, {}, 'Booleans'),
    Variable('tune_852_waveplates_to_target_in_experiment_Node2', False, BooleanValue, {}, 'Booleans'),
    Variable('single_atom_threshold_Node2', 17000.0, NumberValue, {'type': 'float'}, 'Thresholds and cut-offs'),
    Variable('single_atom_threshold_for_loading_Node2', 40000.0, NumberValue, {'type': 'float'}, 'Thresholds and cut-offs'),
    Variable('two_atom_threshold_Node2', 39000.0, NumberValue, {'type': 'float'}, 'Thresholds and cut-offs'),
    Variable('two_atom_threshold_for_loading_Node2', 89000.0, NumberValue, {'type': 'float'}, 'Thresholds and cut-offs'),
    Variable('set_point_PD1_AOM_A1_Node2', 0.06, NumberValue, {'type': 'float', 'ndecimals': 4}, 'Set points'),
    Variable('set_point_PD2_AOM_A2_Node2', 0.45, NumberValue, {'type': 'float', 'ndecimals': 4}, 'Set points'),
    Variable('set_point_PD3_AOM_A3_Node2', 0.06, NumberValue, {'type': 'float', 'ndecimals': 4}, 'Set points'),
    Variable('set_point_PD4_AOM_A4_Node2', 0.45, NumberValue, {'type': 'float', 'ndecimals': 4}, 'Set points'),
    Variable('set_point_PD5_AOM_A5_Node2', 0.8, NumberValue, {'type': 'float', 'ndecimals': 4}, 'Set points'),
    Variable('set_point_PD6_AOM_A6_Node2', 0.8, NumberValue, {'type': 'float', 'ndecimals': 4}, 'Set points'),
    Variable('set_point_FORT_APD_loading_Node2', 0.38, NumberValue, {'type': 'float', 'ndecimals': 5}, 'Set points'),
    Variable('set_point_FORT_APD_science_Node2', 0.13, NumberValue, {'type': 'float', 'ndecimals': 5}, 'Set points'),
    Variable('set_point_FORT_APD_holding_Node2', 0.05, NumberValue, {'type': 'float', 'ndecimals': 5}, 'Set points'),
    Variable('set_point_FORT_MM_loading_Node2', 1.3, NumberValue, {'type': 'float', 'ndecimals': 3}, 'Set points'),
    Variable('set_point_FORT_MM_science_Node2', 0.5, NumberValue, {'type': 'float', 'ndecimals': 3}, 'Set points'),
    Variable('set_point_D1_SP_Node2', 0.175, NumberValue, {'type': 'float', 'ndecimals': 3}, 'Set points'),
    Variable('set_point_excitation_Node2', 1.0, NumberValue, {'type': 'float', 'ndecimals': 3}, 'Set points'),
    Variable('MOT_beam_monitor_points_Node2', 400, NumberValue, {'type': 'int', 'ndecimals': 0, 'scale': 1, 'step': 1}, 'Plotting'),
    Variable('applet_plot_points_short_Node2', 100, NumberValue, {'type': 'int', 'ndecimals': 0, 'scale': 1, 'step': 1}, 'Plotting'),
    Variable('applet_plot_points_medium_Node2', 500, NumberValue, {'type': 'int', 'ndecimals': 0, 'scale': 1, 'step': 1}, 'Plotting'),
    Variable('applet_plot_points_large_Node2', 1000, NumberValue, {'type': 'int', 'ndecimals': 0, 'scale': 1, 'step': 1}, 'Plotting'),
    Variable('ignore_first_n_histogram_points_Node2', 10, NumberValue, {'type': 'int', 'ndecimals': 0, 'scale': 1, 'step': 1}, 'Plotting'),
    Variable('FORT_MM_monitor_sci_ref_volts_Node2', 0.25, NumberValue, {'type': 'float', 'ndecimals': 3, 'scale': 1, 'step': 0.05}, 'Plotting'),
    Variable('second_shot_hist_color_Node2', 'r', StringValue, {}, 'Plotting'),
    Variable('Luca_trigger_for_feedback_verification_Node2', False, BooleanValue, {}, 'Laser feedback'),
    Variable('enable_laser_feedback_Node2', True, BooleanValue, {}, 'Laser feedback'),
    Variable('slow_feedback_dds_list_Node2', '[]', StringValue, {}, 'Laser feedback'),
    Variable('fast_feedback_dds_list_Node2', "['dds_AOM_A1', 'dds_AOM_A2', 'dds_AOM_A3', 'dds_AOM_A4','dds_AOM_A5','dds_AOM_A6','dds_FORT']", StringValue, {}, 'Laser feedback'),
    Variable('aom_feedback_averages_Node2', 20, NumberValue, {'type': 'int', 'ndecimals': 0, 'scale': 1, 'step': 1}, 'Laser feedback'),
    Variable('aom_feedback_iterations_Node2', 100, NumberValue, {'type': 'int', 'ndecimals': 0, 'scale': 1, 'step': 1}, 'Laser feedback'),
    Variable('Rigol_carrier_frequency_Node2', 40000.0, NumberValue, {'type': 'float', 'unit': 'kHz', 'ndecimals': 3}, 'Rigol DG1022Z settings'),
    Variable('Rigol_FM_deviation_Node2', 10000.0, NumberValue, {'type': 'float', 'unit': 'kHz', 'ndecimals': 3}, 'Rigol DG1022Z settings'),
    Variable('Rigol_V_DC_Node2', 0.595, NumberValue, {'type': 'float', 'unit': 'V', 'ndecimals': 3}, 'Rigol DG1022Z settings'),
    Variable('Rigol_V_pp_Node2', 0.03, NumberValue, {'type': 'float', 'unit': 'V', 'ndecimals': 3}, 'Rigol DG1022Z settings'),
    Variable('f_Rigol_modulation_Node2', 10000.0, NumberValue, {'type': 'float', 'unit': 'kHz', 'ndecimals': 3}, 'Rigol DG1022Z settings'),
    Variable('deg_to_pos_Node2', 136533, NumberValue, {'type': 'int', 'ndecimals': 0, 'scale': 1, 'step': 1}, 'K10CR1 Unit Conversion'),
    Variable('target_780_HWP_Node2', 0.0, NumberValue, {'type': 'float', 'ndecimals': 2, 'scale': 1, 'step': 0.5}, 'K10CR1 780 waveplates'),
    Variable('target_780_QWP_Node2', 0.0, NumberValue, {'type': 'float', 'ndecimals': 2, 'scale': 1, 'step': 0.5}, 'K10CR1 780 waveplates'),
    Variable('move_780_HWP_by_Node2', 0.0, NumberValue, {'type': 'float', 'ndecimals': 2, 'scale': 1, 'step': 0.5}, 'K10CR1 780 waveplates'),
    Variable('move_780_QWP_by_Node2', 0.0, NumberValue, {'type': 'float', 'ndecimals': 2, 'scale': 1, 'step': 0.5}, 'K10CR1 780 waveplates'),
    Variable('target_852_HWP_Node2', 0.0, NumberValue, {'type': 'float', 'ndecimals': 2, 'scale': 1, 'step': 0.5}, 'K10CR1 852 waveplates'),
    Variable('target_852_QWP_Node2', 0.0, NumberValue, {'type': 'float', 'ndecimals': 2, 'scale': 1, 'step': 0.5}, 'K10CR1 852 waveplates'),
    Variable('move_852_HWP_by_Node2', 0.0, NumberValue, {'type': 'float', 'ndecimals': 2, 'scale': 1, 'step': 0.5}, 'K10CR1 852 waveplates'),
    Variable('move_852_QWP_by_Node2', 0.0, NumberValue, {'type': 'float', 'ndecimals': 2, 'scale': 1, 'step': 0.5}, 'K10CR1 852 waveplates'),
    Variable('best_852HWP_to_max_Node2', 20.0, NumberValue, {'type': 'float', 'ndecimals': 3, 'scale': 1, 'step': 0.5}, 'K10CR1 852 waveplates'),
    Variable('best_852QWP_to_max_Node2', 3.5, NumberValue, {'type': 'float', 'ndecimals': 3, 'scale': 1, 'step': 0.5}, 'K10CR1 852 waveplates'),
    Variable('best_852_power_Node2', 1.1801237524950101, NumberValue, {'type': 'float', 'ndecimals': 3, 'scale': 1, 'step': 0.5}, 'K10CR1 852 waveplates'),
    Variable('best_852_power_ref_Node2', 1.1703720092773438, NumberValue, {'type': 'float', 'ndecimals': 3, 'scale': 1, 'step': 0.5}, 'K10CR1 852 waveplates'),
    Variable('tolerance_deg_Node2', 0.5, NumberValue, {'type': 'float', 'ndecimals': 3, 'scale': 1, 'step': 0.5}, 'FORT Polarization Stabilization'),
    Variable('full_range_Node2', 45.0, NumberValue, {'type': 'float', 'ndecimals': 3, 'scale': 1, 'step': 0.5}, 'FORT Polarization Stabilization'),
    Variable('sample_pts_Node2', 9, NumberValue, {'type': 'int', 'ndecimals': 0, 'scale': 1, 'step': 1}, 'FORT Polarization Stabilization'),
    Variable('atom_rotation_to_x_Node2', False, BooleanValue, {}, 'Atom Tomography Experiment'),
    Variable('atom_rotation_to_y_Node2', False, BooleanValue, {}, 'Atom Tomography Experiment'),
    Variable('zotino_test1_offset_Node2', -0.14975585937500036, NumberValue, {'type': 'float', 'ndecimals': 5}, 'Zotino'),
    Variable('zotino_test2_offset_Node2', -0.14672241210937464, NumberValue, {'type': 'float', 'ndecimals': 5}, 'Zotino'),
    Variable('zotino_test3_offset_Node2', -0.14939575195312482, NumberValue, {'type': 'float', 'ndecimals': 5}, 'Zotino'),
    Variable('zotino_test4_offset_Node2', -0.14805297851562482, NumberValue, {'type': 'float', 'ndecimals': 5}, 'Zotino'),
    Variable('zotino_test5_offset_Node2', -0.15003051757812536, NumberValue, {'type': 'float', 'ndecimals': 5}, 'Zotino'),
    Variable('zotino_test6_offset_Node2', -0.14313964843749982, NumberValue, {'type': 'float', 'ndecimals': 5}, 'Zotino'),
    Variable('zotino_test7_offset_Node2', -0.14753417968749982, NumberValue, {'type': 'float', 'ndecimals': 5}, 'Zotino'),
    Variable('zotino_test8_offset_Node2', -0.144195556640625, NumberValue, {'type': 'float', 'ndecimals': 5}, 'Zotino'),
    Variable('health_check_uw_freq00_Node2', 0.88, NumberValue, {'type': 'float', 'ndecimals': 5}, 'Microwaves Health Check'),
    Variable('health_check_uw_freq01_Node2', 0.94, NumberValue, {'type': 'float', 'ndecimals': 5}, 'Microwaves Health Check'),
    Variable('health_check_uw_freq11_Node2', 0.89, NumberValue, {'type': 'float', 'ndecimals': 5}, 'Microwaves Health Check'),
    Variable('health_check_uw_freqm10_Node2', 0.88, NumberValue, {'type': 'float', 'ndecimals': 5}, 'Microwaves Health Check'),
    Variable('health_check_uw_freqm11_Node2', 0.88, NumberValue, {'type': 'float', 'ndecimals': 5}, 'Microwaves Health Check'),
    Variable('t_coil_relaxation_time_OP_Node2', 0.0004, NumberValue, {"type": "float", "unit": "ms"}, "Timing"),
)


class ExperimentVariablesMasterSatelliteNode2(EnvExperiment):
    """ExperimentVariables_master_satellite_Node2

    Initialize or intentionally update persistent variables for Node2.
    """

    def build(self):
        self.vars_list = list(NODE2_VARIABLES)
        for variable in self.vars_list:
            try:
                value = self.get_dataset(variable.name)
            except KeyError:
                value = variable.value
            self.setattr_argument(
                variable.name,
                variable.value_type(value, **variable.kwargs),
                variable.group,
            )

    def run(self):
        for variable in self.vars_list:
            self.set_dataset(
                variable.name,
                getattr(self, variable.name),
                broadcast=True,
                persist=True,
            )

        self._set_derived_datasets()

    def _set_derived_datasets(self):
        suffix = "_Node2"
        f_mot = self.get_dataset("f_cooling_DP_MOT" + suffix)
        f_ro = self.get_dataset("f_cooling_DP_RO" + suffix)
        f_pgc = self.get_dataset("f_cooling_DP_PGC" + suffix)
        f_microwaves = self.get_dataset("f_microwaves_dds" + suffix)

        derived = {
            "detuning_MOT_units_Gamma" + suffix:
                (-2 * f_mot + 130e6 + 78.5e6) / 6.065e6,
            "detuning_RO_units_Gamma" + suffix:
                (-2 * f_ro + 130e6 + 78.5e6) / 6.065e6,
            "detuning_PGC_units_Gamma" + suffix:
                (-2 * f_pgc + 130e6 + 78.5e6) / 6.065e6,
            "microwave_frequency_GHz" + suffix: f_microwaves * 1e-9 + 6.5,
            "f_dds_clock_resonance" + suffix: 334.682 * MHz,
        }
        for name, value in derived.items():
            self.set_dataset(name, value, broadcast=True, persist=True)
