from collections import namedtuple

from artiq.experiment import *


Variable = namedtuple("Variable", ["name", "value", "value_type", "kwargs", "group"])


NODE1_VARIABLES = (
    Variable('require_atom_loading_to_advance_Node1', False, BooleanValue, {}, 'general'),
    Variable('require_atom_loading_to_advance_in_single_photon_exp_Node1', False, BooleanValue, {}, 'single photon experiment'),
    Variable('n_excitation_attempts_Node1', 5, NumberValue, {'type': 'int', 'ndecimals': 0, 'step': 1, 'scale': 1}, 'single photon experiment'),
    Variable('max_excitation_cycles_Node1', 2000, NumberValue, {'type': 'int', 'ndecimals': 0, 'step': 1, 'scale': 1}, 'single photon experiment'),
    Variable('atom_check_every_n_Node1', 50, NumberValue, {'type': 'int', 'ndecimals': 0, 'step': 1, 'scale': 1}, 'single photon experiment'),
    Variable('recool_every_n_OP_Node1', 1, NumberValue, {'type': 'int', 'ndecimals': 0, 'step': 1, 'scale': 1}, 'single photon experiment'),
    Variable('record_every_shot_Node1', False, BooleanValue, {}, 'single photon experiment'),
    Variable('dummy_variable_Node1', 0.0, NumberValue, {'type': 'float'}, 'debugging'),
    Variable('monitor_magnetometer_in_end_measurement_Node1', False, BooleanValue, {}, 'debugging'),
    Variable('f_FORT_Node1', 245000000.0, NumberValue, {'type': 'float', 'unit': 'MHz'}, 'FORT AOM'),
    Variable('p_FORT_loading_Node1', -5.2170281158889775, NumberValue, {'type': 'float', 'unit': 'dBm', 'scale': 1, 'ndecimals': 1}, 'FORT AOM'),
    Variable('p_FORT_holding_Node1', 0.5, NumberValue, {'type': 'float', 'unit': '(fractional)', 'scale': 1, 'ndecimals': 2}, 'FORT AOM - outdated'),
    Variable('p_FORT_RO_Node1', 0.8, NumberValue, {'type': 'float', 'unit': '(fractional)', 'scale': 1, 'ndecimals': 1}, 'FORT AOM - outdated'),
    Variable('p_FORT_PGC_Node1', 0.8, NumberValue, {'type': 'float', 'unit': '(fractional)', 'scale': 1, 'ndecimals': 2}, 'FORT AOM - outdated'),
    Variable('p_FORT_blowaway_Node1', 0.7, NumberValue, {'type': 'float', 'unit': '(fractional)', 'scale': 1, 'ndecimals': 2}, 'FORT AOM - outdated'),
    Variable('p_FORT_OP_Node1', 0.8, NumberValue, {'type': 'float', 'unit': '(fractional)', 'scale': 1, 'ndecimals': 2}, 'FORT AOM - outdated'),
    Variable('f_cooling_DP_MOT_Node1', 115000000.0, NumberValue, {'type': 'float', 'unit': 'MHz'}, 'Cooling double pass AOM'),
    Variable('f_cooling_DP_RO_Node1', 120370000.0, NumberValue, {'type': 'float', 'unit': 'MHz'}, 'Cooling double pass AOM'),
    Variable('f_cooling_DP_PGC_Node1', 122700000.0, NumberValue, {'type': 'float', 'unit': 'MHz'}, 'Cooling double pass AOM'),
    Variable('f_cooling_DP_PGC_optimization_Node1', 122040255.81636822, NumberValue, {'type': 'float', 'unit': 'MHz'}, 'Cooling double pass AOM'),
    Variable('f_cooling_DP_resonant_2_to_3_Node1', 104250000.0, NumberValue, {'type': 'float', 'unit': 'MHz'}, 'Cooling double pass AOM'),
    Variable('f_cooling_DP_blowaway_Node1', 104250000.0, NumberValue, {'type': 'float', 'unit': 'MHz'}, 'Cooling double pass AOM'),
    Variable('p_cooling_DP_MOT_Node1', -2.0, NumberValue, {'type': 'float', 'unit': 'dBm', 'scale': 1, 'ndecimals': 1}, 'Cooling double pass AOM'),
    Variable('p_cooling_DP_RO_Node1', 0.5, NumberValue, {'type': 'float', 'unit': '(fractional 0.0 to 1.0)', 'scale': 1, 'ndecimals': 2}, 'Cooling double pass AOM'),
    Variable('p_cooling_DP_PGC_Node1', 0.7, NumberValue, {'type': 'float', 'unit': '(fractional 0.0 to 1.0)', 'scale': 1, 'ndecimals': 2}, 'Cooling double pass AOM'),
    Variable('p_cooling_DP_PGC_optimization_Node1', 0.5, NumberValue, {'type': 'float', 'unit': '(fractional 0.0 to 1.0)', 'scale': 1, 'ndecimals': 2}, 'Cooling double pass AOM'),
    Variable('f_D1_pumping_DP_Node1', 373075000.0, NumberValue, {'type': 'float', 'unit': 'MHz', 'ndecimals': 3}, 'OP and excitation AOMs'),
    Variable('p_D1_pumping_DP_Node1', -1.0, NumberValue, {'type': 'float', 'unit': 'dBm', 'scale': 1, 'ndecimals': 1}, 'OP and excitation AOMs'),
    Variable('f_excitation_Node1', 150500000.0, NumberValue, {'type': 'float', 'unit': 'MHz'}, 'OP and excitation AOMs'),
    Variable('p_excitation_Node1', -5.0, NumberValue, {'type': 'float', 'unit': 'dBm', 'scale': 1, 'ndecimals': 1}, 'OP and excitation AOMs'),
    Variable('max_pumping_cycles_Node1', 10, NumberValue, {'type': 'int', 'ndecimals': 0, 'step': 1, 'scale': 1}, 'Node2 GRIN1 and GRIN2'),
    Variable('f_GRIN1_D1_pumping_Node1', 150500000.0, NumberValue, {'type': 'float', 'unit': 'MHz'}, 'Node2 GRIN1 and GRIN2'),
    Variable('p_GRIN1_D1_pumping_Node1', -8.0, NumberValue, {'type': 'float', 'unit': 'dBm', 'scale': 1, 'ndecimals': 1}, 'Node2 GRIN1 and GRIN2'),
    Variable('f_GRIN2_D1_pumping_Node1', 150600000.0, NumberValue, {'type': 'float', 'unit': 'MHz'}, 'Node2 GRIN1 and GRIN2'),
    Variable('p_GRIN2_D1_pumping_Node1', -8.0, NumberValue, {'type': 'float', 'unit': 'dBm', 'scale': 1, 'ndecimals': 1}, 'Node2 GRIN1 and GRIN2'),
    Variable('f_GRIN1_excitation_Node1', 150500000.0, NumberValue, {'type': 'float', 'unit': 'MHz'}, 'Node2 GRIN1 and GRIN2'),
    Variable('p_GRIN1_excitation_Node1', -8.0, NumberValue, {'type': 'float', 'unit': 'dBm', 'scale': 1, 'ndecimals': 1}, 'Node2 GRIN1 and GRIN2'),
    Variable('f_GRIN2_excitation_Node1', 150600000.0, NumberValue, {'type': 'float', 'unit': 'MHz'}, 'Node2 GRIN1 and GRIN2'),
    Variable('p_GRIN2_excitation_Node1', -8.0, NumberValue, {'type': 'float', 'unit': 'dBm', 'scale': 1, 'ndecimals': 1}, 'Node2 GRIN1 and GRIN2'),
    Variable('AOM_A1_freq_Node1', 78480000.0, NumberValue, {'type': 'float', 'unit': 'MHz', 'ndecimals': 3}, 'Fiber AOMs'),
    Variable('p_AOM_A1_Node1', -12.411580896947223, NumberValue, {'type': 'float', 'unit': 'dBm', 'scale': 1, 'ndecimals': 1}, 'Fiber AOMs'),
    Variable('p_AOM_A1_optimization_Node1', -13.0, NumberValue, {'type': 'float', 'unit': 'dBm', 'scale': 1, 'ndecimals': 1}, 'Fiber AOMs'),
    Variable('AOM_A2_freq_Node1', 78490000.0, NumberValue, {'type': 'float', 'unit': 'MHz', 'ndecimals': 3}, 'Fiber AOMs'),
    Variable('p_AOM_A2_Node1', -11.239549531136301, NumberValue, {'type': 'float', 'unit': 'dBm', 'scale': 1, 'ndecimals': 1}, 'Fiber AOMs'),
    Variable('p_AOM_A2_optimization_Node1', -13.0, NumberValue, {'type': 'float', 'unit': 'dBm', 'scale': 1, 'ndecimals': 1}, 'Fiber AOMs'),
    Variable('AOM_A3_freq_Node1', 78500000.0, NumberValue, {'type': 'float', 'unit': 'MHz', 'ndecimals': 3}, 'Fiber AOMs'),
    Variable('p_AOM_A3_Node1', -11.568343455151737, NumberValue, {'type': 'float', 'unit': 'dBm', 'scale': 1, 'ndecimals': 1}, 'Fiber AOMs'),
    Variable('p_AOM_A3_optimization_Node1', -13.0, NumberValue, {'type': 'float', 'unit': 'dBm', 'scale': 1, 'ndecimals': 1}, 'Fiber AOMs'),
    Variable('AOM_A4_freq_Node1', 78510000.0, NumberValue, {'type': 'float', 'unit': 'MHz', 'ndecimals': 3}, 'Fiber AOMs'),
    Variable('p_AOM_A4_Node1', -11.185016976612818, NumberValue, {'type': 'float', 'unit': 'dBm', 'scale': 1, 'ndecimals': 1}, 'Fiber AOMs'),
    Variable('p_AOM_A4_optimization_Node1', -13.0, NumberValue, {'type': 'float', 'unit': 'dBm', 'scale': 1, 'ndecimals': 1}, 'Fiber AOMs'),
    Variable('AOM_A5_freq_Node1', 78520000.0, NumberValue, {'type': 'float', 'unit': 'MHz', 'ndecimals': 3}, 'Fiber AOMs'),
    Variable('p_AOM_A5_Node1', -17.71290513180519, NumberValue, {'type': 'float', 'unit': 'dBm', 'scale': 1, 'ndecimals': 1}, 'Fiber AOMs'),
    Variable('p_AOM_A5_optimization_Node1', -13.0, NumberValue, {'type': 'float', 'unit': 'dBm', 'scale': 1, 'ndecimals': 1}, 'Fiber AOMs'),
    Variable('AOM_A6_freq_Node1', 78530000.0, NumberValue, {'type': 'float', 'unit': 'MHz', 'ndecimals': 3}, 'Fiber AOMs'),
    Variable('p_AOM_A6_Node1', -18.52324101170499, NumberValue, {'type': 'float', 'unit': 'dBm', 'scale': 1, 'ndecimals': 1}, 'Fiber AOMs'),
    Variable('p_AOM_A6_optimization_Node1', -13.0, NumberValue, {'type': 'float', 'unit': 'dBm', 'scale': 1, 'ndecimals': 1}, 'Fiber AOMs'),
    Variable('f_microwaves_dds_Node1', 334660000.0, NumberValue, {'type': 'float', 'unit': 'MHz', 'ndecimals': 7}, 'Microwaves'),
    Variable('f_microwaves_detuning_Node1', 20000.0, NumberValue, {'type': 'float', 'unit': 'MHz', 'ndecimals': 7}, 'Microwaves'),
    Variable('p_microwaves_Node1', -5.0, NumberValue, {'type': 'float', 'unit': 'dBm', 'scale': 1, 'ndecimals': 1}, 'Microwaves'),
    Variable('f_microwaves_00_dds_Node1', 334659000.0, NumberValue, {'type': 'float', 'unit': 'MHz', 'ndecimals': 7}, 'Microwaves'),
    Variable('f_microwaves_01_dds_Node1', 336950000.0, NumberValue, {'type': 'float', 'unit': 'MHz', 'ndecimals': 7}, 'Microwaves'),
    Variable('f_microwaves_11_dds_Node1', 339213000.0, NumberValue, {'type': 'float', 'unit': 'MHz', 'ndecimals': 7}, 'Microwaves'),
    Variable('f_microwaves_m10_dds_Node1', 332409500.0, NumberValue, {'type': 'float', 'unit': 'MHz', 'ndecimals': 7}, 'Microwaves'),
    Variable('f_microwaves_m11_dds_Node1', 331913000.0, NumberValue, {'type': 'float', 'unit': 'MHz', 'ndecimals': 7}, 'Microwaves'),
    Variable('f_MW_RF_dds_Node1', 2761000.0, NumberValue, {'type': 'float', 'unit': 'MHz', 'ndecimals': 7}, 'Microwaves'),
    Variable('p_MW_RF_dds_Node1', -5.0, NumberValue, {'type': 'float', 'unit': 'dBm', 'scale': 1, 'ndecimals': 1}, 'Microwaves'),
    Variable('t_microwave_pulse_Node1', 3.6e-06, NumberValue, {'type': 'float', 'unit': 'us'}, 'Microwaves'),
    Variable('t_microwave_00_pulse_Node1', 3.6e-06, NumberValue, {'type': 'float', 'unit': 'us'}, 'Microwaves'),
    Variable('t_microwave_01_pulse_Node1', 1.7e-05, NumberValue, {'type': 'float', 'unit': 'us'}, 'Microwaves'),
    Variable('t_microwave_11_pulse_Node1', 4.4e-06, NumberValue, {'type': 'float', 'unit': 'us'}, 'Microwaves'),
    Variable('t_microwave_m10_pulse_Node1', 2.8e-05, NumberValue, {'type': 'float', 'unit': 'us'}, 'Microwaves'),
    Variable('t_microwave_m1m1_pulse_Node1', 6e-06, NumberValue, {'type': 'float', 'unit': 'us'}, 'Microwaves'),
    Variable('t_MW_RF_pulse_Node1', 0.000243, NumberValue, {'type': 'float', 'unit': 'us'}, 'Microwaves'),
    Variable('t_MW_00_ramp_Node1', 2e-06, NumberValue, {'type': 'float', 'unit': 'us'}, 'Microwaves'),
    Variable('t_MW_01_ramp_Node1', 4e-06, NumberValue, {'type': 'float', 'unit': 'us'}, 'Microwaves'),
    Variable('t_MW_11_ramp_Node1', 2e-06, NumberValue, {'type': 'float', 'unit': 'us'}, 'Microwaves'),
    Variable('AZ_bottom_volts_MOT_Node1', 5.967200273927698, NumberValue, {'type': 'float', 'unit': 'V', 'ndecimals': 3}, 'MOT coil settings'),
    Variable('AZ_top_volts_MOT_Node1', 6.385540374379314, NumberValue, {'type': 'float', 'unit': 'V', 'ndecimals': 3}, 'MOT coil settings'),
    Variable('AX_volts_MOT_Node1', -0.10801331267361453, NumberValue, {'type': 'float', 'unit': 'V', 'ndecimals': 3}, 'MOT coil settings'),
    Variable('AY_volts_MOT_Node1', -0.42919894698328526, NumberValue, {'type': 'float', 'unit': 'V', 'ndecimals': 3}, 'MOT coil settings'),
    Variable('AZ_bottom_volts_PGC_Node1', -0.3, NumberValue, {'type': 'float', 'unit': 'V', 'ndecimals': 3}, 'MOT coil settings'),
    Variable('AX_volts_PGC_Node1', 0.0, NumberValue, {'type': 'float', 'unit': 'V', 'ndecimals': 3}, 'MOT coil settings'),
    Variable('AY_volts_PGC_Node1', -0.3, NumberValue, {'type': 'float', 'unit': 'V', 'ndecimals': 3}, 'MOT coil settings'),
    Variable('AZ_bottom_volts_PGC_optimization_Node1', -0.234, NumberValue, {'type': 'float', 'unit': 'V', 'ndecimals': 3}, 'MOT coil settings'),
    Variable('AX_volts_PGC_optimization_Node1', -0.041, NumberValue, {'type': 'float', 'unit': 'V', 'ndecimals': 3}, 'MOT coil settings'),
    Variable('AY_volts_PGC_optimization_Node1', -0.087, NumberValue, {'type': 'float', 'unit': 'V', 'ndecimals': 3}, 'MOT coil settings'),
    Variable('AZ_bottom_volts_OP_Node1', -0.23, NumberValue, {'type': 'float', 'unit': 'V', 'ndecimals': 3}, 'Science coil settings'),
    Variable('AX_volts_OP_Node1', 0.1, NumberValue, {'type': 'float', 'unit': 'V', 'ndecimals': 3}, 'Science coil settings'),
    Variable('AY_volts_OP_Node1', 3.23, NumberValue, {'type': 'float', 'unit': 'V', 'ndecimals': 3}, 'Science coil settings'),
    Variable('AZ_bottom_volts_blowaway_Node1', -0.036, NumberValue, {'type': 'float', 'unit': 'V', 'ndecimals': 3}, 'Science coil settings'),
    Variable('AX_volts_blowaway_Node1', -0.175, NumberValue, {'type': 'float', 'unit': 'V', 'ndecimals': 3}, 'Science coil settings'),
    Variable('AY_volts_blowaway_Node1', -0.036, NumberValue, {'type': 'float', 'unit': 'V', 'ndecimals': 3}, 'Science coil settings'),
    Variable('AZ_bottom_volts_microwave_Node1', -0.23, NumberValue, {'type': 'float', 'unit': 'V', 'ndecimals': 3}, 'Science coil settings'),
    Variable('AX_volts_microwave_Node1', 0.1, NumberValue, {'type': 'float', 'unit': 'V', 'ndecimals': 3}, 'Science coil settings'),
    Variable('AY_volts_microwave_Node1', 3.23, NumberValue, {'type': 'float', 'unit': 'V', 'ndecimals': 3}, 'Science coil settings'),
    Variable('t_MOT_loading_Node1', 1.0, NumberValue, {'type': 'float', 'unit': 'ms'}, 'Timing'),
    Variable('t_FORT_loading_Node1', 0.1, NumberValue, {'type': 'float', 'unit': 'ms'}, 'Timing'),
    Variable('t_FORT_drop_Node1', 0.0, NumberValue, {'type': 'float', 'unit': 'us'}, 'Timing'),
    Variable('t_FORT_modulation_Node1', 0.01, NumberValue, {'type': 'float', 'unit': 'ms'}, 'Timing'),
    Variable('t_FORT_ramp_Node1', 0.001, NumberValue, {'type': 'float', 'unit': 'ms'}, 'Timing'),
    Variable('t_FORT_step_Node1', 9.999999999999999e-06, NumberValue, {'type': 'float', 'unit': 'ms'}, 'Timing'),
    Variable('t_SPCM_exposure_Node1', 0.01, NumberValue, {'type': 'float', 'unit': 'ms'}, 'Timing'),
    Variable('t_atom_check_time_Node1', 0.01, NumberValue, {'type': 'float', 'unit': 'ms'}, 'Timing'),
    Variable('t_SPCM_first_shot_Node1', 0.01, NumberValue, {'type': 'float', 'unit': 'ms'}, 'Timing'),
    Variable('t_SPCM_second_shot_Node1', 0.01, NumberValue, {'type': 'float', 'unit': 'ms'}, 'Timing'),
    Variable('t_SPCM_test_shot_Node1', 0.01, NumberValue, {'type': 'float', 'unit': 'ms'}, 'Timing'),
    Variable('t_SPCM_recool_and_shot_Node1', 0.01, NumberValue, {'type': 'float', 'unit': 'ms'}, 'Timing'),
    Variable('t_delay_between_shots_Node1', 0.0, NumberValue, {'type': 'float', 'unit': 'ms'}, 'Timing'),
    Variable('t_PGC_after_loading_Node1', 0.0006, NumberValue, {'type': 'float', 'unit': 'ms'}, 'Timing'),
    Variable('t_recooling_after_first_shot_Node1', 0.0, NumberValue, {'type': 'float', 'unit': 'us'}, 'Timing'),
    Variable('t_MOT_dissipation_Node1', 0.05, NumberValue, {'type': 'float', 'unit': 'ms'}, 'Timing'),
    Variable('t_blowaway_Node1', 0.00015, NumberValue, {'type': 'float', 'unit': 'us'}, 'Timing'),
    Variable('t_pumping_Node1', 0.0001, NumberValue, {'type': 'float', 'unit': 'us'}, 'Timing'),
    Variable('t_depumping_Node1', 2e-06, NumberValue, {'type': 'float', 'unit': 'us'}, 'Timing'),
    Variable('t_exp_trigger_Node1', 1e-05, NumberValue, {'type': 'float', 'unit': 'ms'}, 'Timing'),
    Variable('t_OP_chop_period_Node1', 1.5e-06, NumberValue, {'type': 'float', 'unit': 'us'}, 'Timing'),
    Variable('t_OP_chop_offset_Node1', 5e-07, NumberValue, {'type': 'float', 'unit': 'us'}, 'Timing'),
    Variable('t_BA_chop_period_Node1', 1.2e-06, NumberValue, {'type': 'float', 'unit': 'us'}, 'Timing'),
    Variable('duty_cycle_OP_Node1', 0.2, NumberValue, {'type': 'float', 'unit': '(fractional 0.0 to 1.0)', 'scale': 1, 'ndecimals': 2}, 'Timing'),
    Variable('duty_cycle_FORT_Node1', 0.65, NumberValue, {'type': 'float', 'unit': '(fractional 0.0 to 1.0)', 'scale': 1, 'ndecimals': 2}, 'Timing'),
    Variable('chop_RO_FORT_off_Node1', 5e-07, NumberValue, {'type': 'float', 'unit': 'us'}, 'Timing'),
    Variable('chop_RO_pulse_length_Node1', 5e-07, NumberValue, {'type': 'float', 'unit': 'us'}, 'Timing'),
    Variable('chop_RO_pulse_offset_Node1', 1e-07, NumberValue, {'type': 'float', 'unit': 'us'}, 'Timing'),
    Variable('chop_RO_gate_length_Node1', 5e-07, NumberValue, {'type': 'float', 'unit': 'us'}, 'Timing'),
    Variable('chop_RO_gate_offset_Node1', 9e-07, NumberValue, {'type': 'float', 'unit': 'us'}, 'Timing'),
    Variable('t_recooling_Node1', 0.0006, NumberValue, {'type': 'float', 'unit': 'ms'}, 'Timing'),
    Variable('t_photon_collection_time_Node1', 1.0000000000000001e-07, NumberValue, {'type': 'float', 'unit': 'ns'}, 'Timing'),
    Variable('gate_start_offset_mu_Node1', 660, NumberValue, {'type': 'int', 'ndecimals': 0, 'scale': 1, 'step': 1}, 'Timing'),
    Variable('t_excitation_pulse_Node1', 3.0000000000000004e-08, NumberValue, {'type': 'float', 'unit': 'ns'}, 'Timing'),
    Variable('t_excitation_offset_mu_Node1', -330, NumberValue, {'type': 'int', 'ndecimals': 0, 'scale': 1, 'step': 1}, 'Timing'),
    Variable('t_start_MW_mapping_mu_Node1', 10000, NumberValue, {'type': 'int', 'ndecimals': 0, 'scale': 1, 'step': 1}, 'Timing'),
    Variable('no_first_shot_Node1', False, BooleanValue, {}, 'Booleans'),
    Variable('do_PGC_after_loading_Node1', True, BooleanValue, {}, 'Booleans'),
    Variable('pumping_light_off_Node1', False, BooleanValue, {}, 'Booleans'),
    Variable('blowaway_light_off_Node1', False, BooleanValue, {}, 'Booleans'),
    Variable('FORT_on_at_MOT_start_Node1', True, BooleanValue, {}, 'Booleans'),
    Variable('D1_off_in_OP_phase_Node1', False, BooleanValue, {}, 'Booleans'),
    Variable('D1_off_in_depump_phase_Node1', False, BooleanValue, {}, 'Booleans'),
    Variable('require_D1_lock_to_advance_Node1', False, BooleanValue, {}, 'Booleans'),
    Variable('use_chopped_readout_Node1', False, BooleanValue, {}, 'Booleans'),
    Variable('chopped_RO_light_off_Node1', False, BooleanValue, {}, 'Booleans'),
    Variable('verify_OP_in_photon_experiment_Node1', False, BooleanValue, {}, 'Booleans'),
    Variable('monitors_for_atom_loading_Node1', False, BooleanValue, {}, 'Booleans'),
    Variable('PGC_and_RO_with_on_chip_beams_Node1', True, BooleanValue, {}, 'Booleans'),
    Variable('tune_shims_when_loading_is_bad_Node1', False, BooleanValue, {}, 'Booleans'),
    Variable('tune_852_waveplates_to_target_in_experiment_Node1', False, BooleanValue, {}, 'Booleans'),
    Variable('single_atom_threshold_Node1', 14000.0, NumberValue, {'type': 'float'}, 'Thresholds and cut-offs'),
    Variable('single_atom_threshold_for_loading_Node1', 44000.0, NumberValue, {'type': 'float'}, 'Thresholds and cut-offs'),
    Variable('two_atom_threshold_Node1', 39000.0, NumberValue, {'type': 'float'}, 'Thresholds and cut-offs'),
    Variable('two_atom_threshold_for_loading_Node1', 89000.0, NumberValue, {'type': 'float'}, 'Thresholds and cut-offs'),
    Variable('set_point_PD1_AOM_A1_Node1', 0.22000000000000003, NumberValue, {'type': 'float', 'ndecimals': 4}, 'Set points'),
    Variable('set_point_PD2_AOM_A2_Node1', 0.19799686232465835, NumberValue, {'type': 'float', 'ndecimals': 4}, 'Set points'),
    Variable('set_point_PD3_AOM_A3_Node1', 0.21705300033549457, NumberValue, {'type': 'float', 'ndecimals': 4}, 'Set points'),
    Variable('set_point_PD4_AOM_A4_Node1', 0.21873580893798517, NumberValue, {'type': 'float', 'ndecimals': 4}, 'Set points'),
    Variable('set_point_PD5_AOM_A5_Node1', 0.09699085238589572, NumberValue, {'type': 'float', 'ndecimals': 4}, 'Set points'),
    Variable('set_point_PD6_AOM_A6_Node1', 0.09000000000000001, NumberValue, {'type': 'float', 'ndecimals': 4}, 'Set points'),
    Variable('set_point_FORT_APD_loading_Node1', 1.16, NumberValue, {'type': 'float', 'ndecimals': 5}, 'Set points'),
    Variable('set_point_FORT_APD_science_Node1', 0.3, NumberValue, {'type': 'float', 'ndecimals': 5}, 'Set points'),
    Variable('set_point_FORT_APD_holding_Node1', 0.05, NumberValue, {'type': 'float', 'ndecimals': 5}, 'Set points'),
    Variable('set_point_FORT_MM_loading_Node1', 0.3, NumberValue, {'type': 'float', 'ndecimals': 3}, 'Set points'),
    Variable('set_point_FORT_MM_science_Node1', 0.15, NumberValue, {'type': 'float', 'ndecimals': 3}, 'Set points'),
    Variable('set_point_D1_SP_Node1', 0.2, NumberValue, {'type': 'float', 'ndecimals': 3}, 'Set points'),
    Variable('set_point_excitation_Node1', 0.1, NumberValue, {'type': 'float', 'ndecimals': 3}, 'Set points'),
    Variable('MOT_beam_monitor_points_Node1', 200, NumberValue, {'type': 'int', 'ndecimals': 0, 'scale': 1, 'step': 1}, 'Plotting'),
    Variable('applet_plot_points_short_Node1', 100, NumberValue, {'type': 'int', 'ndecimals': 0, 'scale': 1, 'step': 1}, 'Plotting'),
    Variable('applet_plot_points_medium_Node1', 500, NumberValue, {'type': 'int', 'ndecimals': 0, 'scale': 1, 'step': 1}, 'Plotting'),
    Variable('applet_plot_points_large_Node1', 1000, NumberValue, {'type': 'int', 'ndecimals': 0, 'scale': 1, 'step': 1}, 'Plotting'),
    Variable('ignore_first_n_histogram_points_Node1', 10, NumberValue, {'type': 'int', 'ndecimals': 0, 'scale': 1, 'step': 1}, 'Plotting'),
    Variable('FORT_MM_monitor_sci_ref_volts_Node1', 0.25, NumberValue, {'type': 'float', 'ndecimals': 3, 'scale': 1, 'step': 0.05}, 'Plotting'),
    Variable('second_shot_hist_color_Node1', 'r', StringValue, {}, 'Plotting'),
    Variable('Luca_trigger_for_feedback_verification_Node1', False, BooleanValue, {}, 'Laser feedback'),
    Variable('enable_laser_feedback_Node1', True, BooleanValue, {}, 'Laser feedback'),
    Variable('slow_feedback_dds_list_Node1', '[]', StringValue, {}, 'Laser feedback'),
    Variable('fast_feedback_dds_list_Node1', "['dds_AOM_A1','dds_AOM_A2','dds_AOM_A3','dds_AOM_A4','dds_AOM_A5','dds_AOM_A6','dds_FORT']", StringValue, {}, 'Laser feedback'),
    Variable('aom_feedback_averages_Node1', 20, NumberValue, {'type': 'int', 'ndecimals': 0, 'scale': 1, 'step': 1}, 'Laser feedback'),
    Variable('aom_feedback_iterations_Node1', 200, NumberValue, {'type': 'int', 'ndecimals': 0, 'scale': 1, 'step': 1}, 'Laser feedback'),
    Variable('Rigol_carrier_frequency_Node1', 65000.0, NumberValue, {'type': 'float', 'unit': 'kHz', 'ndecimals': 3}, 'Rigol DG1022Z settings'),
    Variable('Rigol_FM_deviation_Node1', 35000.0, NumberValue, {'type': 'float', 'unit': 'kHz', 'ndecimals': 3}, 'Rigol DG1022Z settings'),
    Variable('Rigol_V_DC_Node1', 0.595, NumberValue, {'type': 'float', 'unit': 'V', 'ndecimals': 3}, 'Rigol DG1022Z settings'),
    Variable('Rigol_V_pp_Node1', 0.05, NumberValue, {'type': 'float', 'unit': 'V', 'ndecimals': 3}, 'Rigol DG1022Z settings'),
    Variable('f_Rigol_modulation_Node1', 10000.0, NumberValue, {'type': 'float', 'unit': 'kHz', 'ndecimals': 3}, 'Rigol DG1022Z settings'),
    Variable('deg_to_pos_Node1', 136533, NumberValue, {'type': 'int', 'ndecimals': 0, 'scale': 1, 'step': 1}, 'K10CR1 Unit Conversion'),
    Variable('target_780_HWP_Node1', 0.0, NumberValue, {'type': 'float', 'ndecimals': 2, 'scale': 1, 'step': 0.5}, 'K10CR1 780 waveplates'),
    Variable('target_780_QWP_Node1', 0.0, NumberValue, {'type': 'float', 'ndecimals': 2, 'scale': 1, 'step': 0.5}, 'K10CR1 780 waveplates'),
    Variable('move_780_HWP_by_Node1', 0.0, NumberValue, {'type': 'float', 'ndecimals': 2, 'scale': 1, 'step': 0.5}, 'K10CR1 780 waveplates'),
    Variable('move_780_QWP_by_Node1', 0.0, NumberValue, {'type': 'float', 'ndecimals': 2, 'scale': 1, 'step': 0.5}, 'K10CR1 780 waveplates'),
    Variable('target_852_HWP_Node1', 0.0, NumberValue, {'type': 'float', 'ndecimals': 2, 'scale': 1, 'step': 0.5}, 'K10CR1 852 waveplates'),
    Variable('target_852_QWP_Node1', 0.0, NumberValue, {'type': 'float', 'ndecimals': 2, 'scale': 1, 'step': 0.5}, 'K10CR1 852 waveplates'),
    Variable('move_852_HWP_by_Node1', 0.0, NumberValue, {'type': 'float', 'ndecimals': 2, 'scale': 1, 'step': 0.5}, 'K10CR1 852 waveplates'),
    Variable('move_852_QWP_by_Node1', 0.0, NumberValue, {'type': 'float', 'ndecimals': 2, 'scale': 1, 'step': 0.5}, 'K10CR1 852 waveplates'),
    Variable('best_852HWP_to_max_Node1', -8.0, NumberValue, {'type': 'float', 'ndecimals': 3, 'scale': 1, 'step': 0.5}, 'K10CR1 852 waveplates'),
    Variable('best_852QWP_to_max_Node1', -10.0, NumberValue, {'type': 'float', 'ndecimals': 3, 'scale': 1, 'step': 0.5}, 'K10CR1 852 waveplates'),
    Variable('best_852_power_Node1', 0.48288806268468754, NumberValue, {'type': 'float', 'ndecimals': 3, 'scale': 1, 'step': 0.5}, 'K10CR1 852 waveplates'),
    Variable('best_852_power_ref_Node1', 0.4894866943359375, NumberValue, {'type': 'float', 'ndecimals': 3, 'scale': 1, 'step': 0.5}, 'K10CR1 852 waveplates'),
    Variable('tolerance_deg_Node1', 0.5, NumberValue, {'type': 'float', 'ndecimals': 3, 'scale': 1, 'step': 0.5}, 'FORT Polarization Stabilization'),
    Variable('full_range_Node1', 45.0, NumberValue, {'type': 'float', 'ndecimals': 3, 'scale': 1, 'step': 0.5}, 'FORT Polarization Stabilization'),
    Variable('sample_pts_Node1', 9, NumberValue, {'type': 'int', 'ndecimals': 0, 'scale': 1, 'step': 1}, 'FORT Polarization Stabilization'),
    Variable('atom_rotation_to_x_Node1', False, BooleanValue, {}, 'Atom Tomography Experiment'),
    Variable('atom_rotation_to_y_Node1', False, BooleanValue, {}, 'Atom Tomography Experiment'),
    Variable('zotino_test1_offset_Node1', 0.0, NumberValue, {'type': 'float', 'ndecimals': 5}, 'Zotino'),
    Variable('zotino_test2_offset_Node1', 0.0, NumberValue, {'type': 'float', 'ndecimals': 5}, 'Zotino'),
    Variable('zotino_test3_offset_Node1', 0.0, NumberValue, {'type': 'float', 'ndecimals': 5}, 'Zotino'),
    Variable('zotino_test4_offset_Node1', 0.0, NumberValue, {'type': 'float', 'ndecimals': 5}, 'Zotino'),
    Variable('zotino_test5_offset_Node1', 0.0, NumberValue, {'type': 'float', 'ndecimals': 5}, 'Zotino'),
    Variable('zotino_test6_offset_Node1', 0.0, NumberValue, {'type': 'float', 'ndecimals': 5}, 'Zotino'),
    Variable('zotino_test7_offset_Node1', 0.0, NumberValue, {'type': 'float', 'ndecimals': 5}, 'Zotino'),
    Variable('zotino_test8_offset_Node1', 0.0, NumberValue, {'type': 'float', 'ndecimals': 5}, 'Zotino'),
    Variable('health_check_uw_freq00_Node1', 0.78, NumberValue, {'type': 'float', 'ndecimals': 5}, 'Microwaves Health Check'),
    Variable('health_check_uw_freq01_Node1', 0.06, NumberValue, {'type': 'float', 'ndecimals': 5}, 'Microwaves Health Check'),
    Variable('health_check_uw_freq11_Node1', 1.0, NumberValue, {'type': 'float', 'ndecimals': 5}, 'Microwaves Health Check'),
    Variable('health_check_uw_freqm10_Node1', 0.0, NumberValue, {'type': 'float', 'ndecimals': 5}, 'Microwaves Health Check'),
    Variable('health_check_uw_freqm11_Node1', 0.0, NumberValue, {'type': 'float', 'ndecimals': 5}, 'Microwaves Health Check'),
    Variable('t_coil_relaxation_time_OP_Node1', 0.001, NumberValue, {"type": "float", "unit": "ms"}, "Timing"),
)


class ExperimentVariablesNode1(EnvExperiment):
    """Initialize or intentionally update persistent variables for Node1."""

    def build(self):
        self.vars_list = list(NODE1_VARIABLES)
        for variable in self.vars_list:
            try:
                value = self.get_dataset(variable.name)
            except KeyError:
                value = variable.value
            self.setattr_argument(
                variable.name,
                variable.value_type(value, **variable.kwargs),
                variable.group,
            )

    def run(self):
        for variable in self.vars_list:
            self.set_dataset(
                variable.name,
                getattr(self, variable.name),
                broadcast=True,
                persist=True,
            )

        self._set_derived_datasets()

    def _set_derived_datasets(self):
        suffix = "_Node1"
        f_mot = self.get_dataset("f_cooling_DP_MOT" + suffix)
        f_ro = self.get_dataset("f_cooling_DP_RO" + suffix)
        f_pgc = self.get_dataset("f_cooling_DP_PGC" + suffix)
        f_microwaves = self.get_dataset("f_microwaves_dds" + suffix)

        derived = {
            "detuning_MOT_units_Gamma" + suffix:
                (-2 * f_mot + 130e6 + 78.5e6) / 6.065e6,
            "detuning_RO_units_Gamma" + suffix:
                (-2 * f_ro + 130e6 + 78.5e6) / 6.065e6,
            "detuning_PGC_units_Gamma" + suffix:
                (-2 * f_pgc + 130e6 + 78.5e6) / 6.065e6,
            "microwave_frequency_GHz" + suffix: f_microwaves * 1e-9 + 6.5,
            "f_dds_clock_resonance" + suffix: 334.682 * MHz,
        }
        for name, value in derived.items():
            self.set_dataset(name, value, broadcast=True, persist=True)
