"""
some functions that streamline working with h5 files generated by ARTIQ experiments
as well as some functions for plotting
"""

import numpy as np
import os
import h5py
import matplotlib as mpl
from matplotlib import pyplot as plt
from matplotlib.ticker import FormatStrFormatter
import matplotlib.colors as mcolors
from skimage.filters import threshold_otsu

results = "C:\\Networking Experiment\\artiq codes\\artiq-master\\results\\"

MHz = 1e6
kHz = 1e3
ms = 1e-3
us = 1e-6
V = 1

###  Colors for plots
color0 = (20/255, 20/255, 20/255)  # soft black
color1 = (1/255, 120/255, 240/255)  # blue
color2 = (185/255, 46/255, 46/255)   # red
color3 = (20/255, 145/255, 1/255)   # green




##### plot helper

def lighten(color, amount=0.6, on="white"):
    """
    Return a lighter color by blending 'color' toward 'on' (default: white).
    amount in [0,1]: 0 => original color, 1 => fully 'on'.
    """
    c = np.array(mcolors.to_rgb(color))
    o = np.array(mcolors.to_rgb(on))
    out = (1.0 - amount) * c + amount * o
    return tuple(np.clip(out, 0.0, 1.0))
    
def plot_series_with_fit(
    series,
    title="",
    xlabel="",
    ylabel="",
    xlim=None,
    ylim=None,
    legend_out=True,                 # place legend outside by default 
    legend_loc=(1.05, 0.2),          # (x, y) in axes coords when legend_out=True
    legend_kw=None,                  # extra kwargs to ax.legend(...)
    figsize=(8, 4),
    save=None,
    show=True,
    grid=False,
    suppress_sci_x=True,             # turn off "×1e^k" on x-axis
    x_format="%.1f",                 # x tick label format (if suppress_sci_x)
):
    """
    Generic 2D plotter for data + error bars + optional fit curve(s).

    Parameters
    ----------
    series : list[dict]
        Each dict describes one trace:
            Required keys:
              - 'x'     : 1D array-like (x-values)
              - 'y'     : 1D array-like (y-values)
              - 'yerr'  : 1D array-like (sym) or shape (2, N) (asym) or None
              - 'label' : str (legend label)
            Optional keys (with sensible defaults):
              - 'fit'       : tuple (x_fit, y_fit) or None
              - 'color'     : matplotlib color spec; default: auto cycle
              - 'marker'    : e.g., 'o' (default)
              - 'ms'        : markersize (default 8)
              - 'lw'        : errorbar/line width (default 1.5)
              - 'capsize'   : errorbar cap size (default 4)
              - 'zorder'    : drawing order (default 3 for points)
              - 'mfc'       : marker facecolor (default 'white' for hollow)
              - 'mec'       : marker edgecolor (default = color)
              - 'ecolor'    : errorbar color (default = color)
              - 'fit_style' : dict for fit line (e.g., {'linestyle':'-', 'linewidth':1.6})
    Other parameters control figure/axes cosmetics and saving.
    """
    fig, ax = plt.subplots(figsize=figsize)

    for i, s in enumerate(series):
        x      = s["x"]
        y      = s["y"]
        yerr   = s.get("yerr", None)
        label  = s.get("label", f"Series {i}")

        color  = s.get("color", None)
        marker = s.get("marker", "o")
        ms     = s.get("ms", 6)
        lw     = s.get("lw", 1.5)
        capsz  = s.get("capsize", 2)
        z      = s.get("zorder", 3)

        #### marker styling
        #### fill with a LIGHTER shade of the edge color.
        lighten_amount = s.get("lighten_amount", 0.80)   # 80% toward white
        mfc_color    = lighten(color, amount=lighten_amount)
        fit_color    = lighten(color, amount=0.5)
        
        # mfc    = s.get("mfc", "white")
        mfc    = s.get("mfc", mfc_color if color is not None else None)
        mec    = s.get("mec", color if color is not None else None)
        ecolor = s.get("ecolor", color if color is not None else None)

        # --- data with error bars (accepts sym or asym yerr) ---
        ax.errorbar(
            x, y, yerr=yerr, label=label, fmt=marker,
            mfc=mfc, mec=mec, ecolor=ecolor,
            capsize=capsz, markersize=ms, linewidth=lw, zorder=z
        )

        # --- optional fit curve ---
        fit = s.get("fit", None)
        if fit is not None:
            xf, yf = fit
            fit_style = {"linestyle": "-", "linewidth": 1.6}
            fit_style.update(s.get("fit_style", {}))
            ax.plot(xf, yf, color=fit_color, zorder=z, **fit_style)

    # ----- axes cosmetics -----
    ax.set_xlabel(xlabel)
    ax.set_ylabel(ylabel)
    if xlim is not None: ax.set_xlim(xlim)
    if ylim is not None: ax.set_ylim(ylim)
    ax.set_title(title)

    if grid:
        ax.grid(True, which='both', alpha=0.25)

    # Turn off "×1e^k" offset on x-axis and format ticks plainly
    if suppress_sci_x:
        ax.ticklabel_format(style='plain', axis='x', useOffset=False)
        ax.xaxis.set_major_formatter(FormatStrFormatter(x_format))

    # Legend either outside or inside
    if legend_out:
        # place just outside the right edge (like your parity helper)
        lk = dict(frameon=False, bbox_to_anchor=legend_loc, loc='upper left')
    else:
        lk = dict(frameon=False, loc='best')
    if legend_kw:
        lk.update(legend_kw)
    ax.legend(**lk)

    fig.tight_layout()

    if save:
        fig.savefig(save, bbox_inches="tight")

    if show:
        plt.show()
        plt.close(fig)
        return None
    else:
        return fig, ax



def binomial_err(n_loaded, retention):
    """returns the the binomial error for atom retention data given the number of atoms loaded"""
    return np.sqrt(n_loaded*retention*(1-retention))/n_loaded # sqrt(n*p*(1-p))/n

def eval_str_from_h5(h5_str):
    """a stupid way to evaluate python evaluable strings I saved as ARTIQ datasets"""
    return eval(str(np.array(h5_str))[2:-1])

def str_from_h5(h5_str):
    """a stupid way to read strings I saved as ARTIQ datasets"""
    return str(np.array(h5_str))[2:-1]

# from https://stackoverflow.com/questions/37765197/darken-or-lighten-a-color-in-matplotlib
def lighten_color(color, amount=0.5):
    """
    Lightens the given color by multiplying (1-luminosity) by the given amount.
    Input can be matplotlib color string, hex string, or RGB tuple.

    Examples:
    >> lighten_color('g', 0.3)
    >> lighten_color('#F034A3', 0.6)
    >> lighten_color((.3,.55,.1), 0.5)
    """
    import matplotlib.colors as mc
    import colorsys
    try:
        c = mc.cnames[color]
    except:
        c = color
    c = colorsys.rgb_to_hls(*mc.to_rgb(c))
    return colorsys.hls_to_rgb(c[0], 1 - amount * (1 - c[1]), c[2])
    

def get_files_by_criteria(date_filters, name_filters, condition,
                          start_dir=results, include_path=True, print_filenames=False):
    file_list = []
    for root, dirs, files in os.walk(start_dir, topdown=False):
        for name in files:
            # Check if root contains any of the date filters
            if any(x in root for x in date_filters):
                if any(x in name for x in name_filters):
                    filename = os.path.join(root, name)
                    try:
                        h5py.File(filename)
                        if condition(filename):
                            if not include_path:
                                filename = name
                            if print_filenames:
                                print(filename)
                            file_list.append(filename)
                    except OSError:
                        print(f"skipping {filename}, which is corrupt")
    return file_list

def get_files_by_multiple_names(date_filters, name_filters, **kwargs):
    """
    Call get_files_by_criteria once for each name_filter
    and merge the results without duplicates.

    Useful now that result filenames carry a node tag: pass e.g.
    ["_Node1_atom_loading", "_Node2_atom_loading"] to pull both nodes at once,
    or a single tag to pull one node.
    """
    combined = set()
    for nf in name_filters:
        fnames = get_files_by_criteria(
            date_filters=date_filters,
            name_filters=[nf],   # single filter -> original logic unchanged
            condition=kwargs.get("condition", lambda x: True),
            start_dir=kwargs.get("start_dir", results),
            include_path=kwargs.get("include_path", True),
            print_filenames=kwargs.get("print_filenames", False),
        )
        combined.update(fnames)

    return list(combined)


###############################################################################
###  master-satellite helpers, for Analysis/master_satellite/
###
###  Everything above is untouched: these are new functions, so the standalone
###  notebooks in Analysis/standalone/ behave exactly as they always did.
###
###  The point of all this is that ONE notebook can analyse either node. A
###  master-satellite run writes its ExperimentVariables node-suffixed
###  (single_atom_threshold_Node2) while the bulk readouts stay plain
###  (AllSPCMs_RO1). Strip the suffix on load and the notebook body can be
###  written once, against unsuffixed names, exactly like the standalone code.
###############################################################################

MASTER_SATELLITE_NODES = ("Node1", "Node2")

#: Default file filters, so a master-satellite query cannot accidentally pick
#: up standalone runs -- "GeneralVariableScan" alone matches both.
MASTER_SATELLITE_NAME_FILTERS = (
    "GeneralVariableScan_master_satellite",
    "MicrowaveScanOptimizer_master_satellite",
    "AOMsCoils_master_satellite",
)


def _ms_expid_arguments(f):
    """Submitted arguments from the h5's expid, or {} if unreadable."""
    # Imported locally so the top of this module stays byte-identical to what
    # the standalone notebooks have always imported.
    import json

    try:
        return json.loads(f["expid"][()])["arguments"]
    except Exception:
        return {}


def ms_node_of(f, filename=None):
    """Return 'Node1' or 'Node2' for a master-satellite h5 file.

    Three sources are tried, most reliable first:

      1. expid arguments -- selected_node (GVS) or which_node (optimizers).
         Recorded for every master-satellite run there has ever been, so this
         works on old files too, not just ones with the node in the filename.
      2. the node tag in the filename, present from 2026-09-17 onward.
      3. the node suffix on the dataset/archive keys themselves.

    Returns None if the file has no node information at all, which is what a
    standalone file looks like.

    Raises ValueError if BOTH node suffixes appear, because then stripping
    them would collide and one node's data would silently overwrite the
    other's. No such file exists today (all 89 checked carry exactly one
    node), but a future two-node run would, and it must fail loudly.
    """
    arguments = _ms_expid_arguments(f)
    # The equality below is EXACT on purpose, and it is load-bearing. The
    # standalone stack also submits a which_node argument, but spells it in
    # the legacy presentation: 2403 archived standalone runs carry
    # which_node='alice' (2394) or 'bob' (9). Only the master-satellite stack
    # says Node1/Node2 -- FORT_Polarization_Optimizer says node1/node2, hence
    # the .lower(). Loosening this to something like `if value: return value`
    # would quietly reclassify every one of those standalone runs as a
    # master-satellite one.
    for key in ("selected_node", "which_node"):
        value = str(arguments.get(key) or "")
        for node in MASTER_SATELLITE_NODES:
            if value.lower() == node.lower():
                return node

    name = filename or getattr(f, "filename", "") or ""
    name = str(name)
    for node in MASTER_SATELLITE_NODES:
        if f"_{node}_" in name or name.endswith(f"_{node}.h5"):
            return node

    seen = set()
    for data_level in ("datasets", "archive"):
        if data_level not in f:
            continue
        for key in f[data_level].keys():
            for node in MASTER_SATELLITE_NODES:
                if key.endswith("_" + node):
                    seen.add(node)
    if len(seen) > 1:
        raise ValueError(
            f"{name or 'file'} carries both {sorted(seen)} suffixes; "
            "stripping them would collide. Analyse it with the plain "
            "h5_archive_and_datasets_to_locals and address the nodes by "
            "their suffixed names instead."
        )
    return seen.pop() if seen else None


def ms_files(date_filters, node=None, name_filters=None, **kwargs):
    """Find master-satellite result files and report each one's node.

    Returns a list of (filename, node) pairs sorted by path, which for the
    date-based results tree is effectively chronological. Pass node="Node1"
    or "Node2" to keep only that node's runs.

    name_filters defaults to MASTER_SATELLITE_NAME_FILTERS so standalone runs
    are never mixed in.
    """
    if name_filters is None:
        name_filters = list(MASTER_SATELLITE_NAME_FILTERS)

    found = get_files_by_multiple_names(date_filters, name_filters, **kwargs)

    pairs = []
    for filename in sorted(found):
        try:
            with h5py.File(filename, "r") as handle:
                this_node = ms_node_of(handle, filename=filename)
        except Exception as error:
            print(f"skipping {filename}: {error}")
            continue
        if node is not None and this_node != node:
            continue
        pairs.append((filename, this_node))
    return pairs


def _ms_decode(value):
    """bytes -> str, 0-d array -> its scalar, anything else unchanged."""
    if isinstance(value, bytes):
        return value.decode("utf-8", "replace")
    if isinstance(value, np.ndarray) and value.shape == ():
        return _ms_decode(value[()])
    return value


def _ms_handle(source):
    """(handle, handle_to_close) for either an open h5py.File or a path."""
    if isinstance(source, (str, bytes, os.PathLike)):
        opened = h5py.File(source, "r")
        return opened, opened
    return source, None


def ms_get(source, key, default=None):
    """Read one value from a master-satellite result file.

    Resolves in the same precedence ms_archive_and_datasets_to_locals uses:
    datasets, then archive, then the submitted expid arguments.

    That last step is exactly what the direct h5py subscripts in these
    notebooks were missing. GeneralVariableScan_master_satellite does NOT
    archive scan_variable1_name as a dataset the way the standalone stack
    does -- it survives only in expid["arguments"] -- and n_measurements
    lives in archive rather than datasets. So ds['scan_variable1_name']
    raises, and because the surrounding try wore a bare `except:`, every
    master-satellite GVS run was reported as "oops... something wrong with"
    rather than as a missing name. Nothing was wrong with those files.

    Node suffixes are resolved, so the bare name works whichever node wrote
    the file.

    Strings come back DECODED. Do not wrap the result in str_from_h5: that is
    a bytes-repr trick, str(np.array(x))[2:-1], and handed an already-decoded
    str it silently returns a single character.

    source may be an open h5py.File or a path.
    """
    handle, to_close = _ms_handle(source)
    try:
        try:
            node = ms_node_of(handle)
        except Exception:
            node = None

        names = [key] if node is None else [key, f"{key}_{node}"]
        for container in ("datasets", "archive"):
            if container not in handle:
                continue
            group = handle[container]
            for name in names:
                if name in group:
                    return _ms_decode(group[name][()])

        arguments = _ms_expid_arguments(handle)
        for name in names:
            if name in arguments:
                return arguments[name]
        return default
    finally:
        if to_close is not None:
            to_close.close()


def ms_scan_label(source):
    """The "scanned over ..." label for a master-satellite result file.

    Returns "f_FORT" or "f_FORT, t_FORT", or "" if the run recorded no scan
    variable. Opens the file once, unlike reading the two names separately.
    """
    handle, to_close = _ms_handle(source)
    try:
        first = ms_get(handle, "scan_variable1_name", "") or ""
        second = ms_get(handle, "scan_variable2_name", "") or ""
        return f"{first}, {second}" if second else first
    finally:
        if to_close is not None:
            to_close.close()


def ms_overrides(source):
    """Each node's submitted override dictionary, as {node: text}.

    The experiments declare one override dictionary PER NODE --
    override_ExperimentVariables_Node1 and override_ExperimentVariables_Node2
    -- so a run records BOTH, the running node's and the idle node's. Read
    them by those two names; there is deliberately no unsuffixed
    override_ExperimentVariables to fall back on, because with two
    dictionaries present a bare name cannot say which node it describes.

    Runs from before each node got its own dictionary carry a single
    unsuffixed override_ExperimentVariables instead. Those come back under the
    key "unsuffixed", so one notebook cell reads both generations: of the
    node-tagged GVS files on disk, 18 are of the older shape and 12 of the
    newer, so this is not a transitional nicety.

    Returns {} for a run that recorded no override argument at all.
    """
    handle, to_close = _ms_handle(source)
    try:
        arguments = _ms_expid_arguments(handle)
        found = {
            node: arguments[f"override_ExperimentVariables_{node}"]
            for node in MASTER_SATELLITE_NODES
            if f"override_ExperimentVariables_{node}" in arguments
        }
        if found:
            return found
        if "override_ExperimentVariables" in arguments:
            return {"unsuffixed": arguments["override_ExperimentVariables"]}
        return {}
    finally:
        if to_close is not None:
            to_close.close()


def ms_print_overrides(source, label="override"):
    """Print each node's submitted override dictionary, one line per node.

    Replaces the `print("override:", override_ExperimentVariables)` line the
    ported notebooks carried. That name no longer exists: each node has its
    own dictionary now, and this prints both.
    """
    found = ms_overrides(source)
    if not found:
        print(f"{label}: (none recorded)")
    for key in sorted(found):
        print(f"{label} {key}:", found[key])
    return found


def ms_show_node(source, size_px=26):
    """Show, prominently, which node a result file came from.

    The node decides which half of the apparatus every number in the file
    describes, so it belongs ABOVE the run's details rather than among them.
    Rendered as large HTML in a notebook and as a plain banner anywhere else,
    so the same call works from a script.

    Returns the node, or None for a file carrying no node information -- which
    is what a standalone run looks like.
    """
    handle, to_close = _ms_handle(source)
    try:
        try:
            node = ms_node_of(handle)
        except Exception:
            node = None
    finally:
        if to_close is not None:
            to_close.close()

    label = node or "no node recorded"
    # Distinct hues so the two nodes are told apart at a glance. Both are
    # mid-tone, which keeps them legible on a light or a dark notebook theme.
    color = {"Node1": "#1a7ae0", "Node2": "#d2452e"}.get(node, "#8a8a8a")

    try:
        from IPython import get_ipython
        from IPython.display import display, HTML
        in_notebook = get_ipython() is not None
    except Exception:
        in_notebook = False

    if not in_notebook:
        print(f"===== {label} =====")
        return node

    display(HTML(
        f"<div style='font-size:{size_px}px; font-weight:700; color:{color};"
        f" letter-spacing:0.5px; margin:6px 0 2px'>{label}</div>"
    ))
    return node


def ms_archive_and_datasets_to_locals(f, parent_locals, quiet=False,
                                      node=None):
    """Master-satellite loader. Same signature as the standalone one.

    Swapping h5_archive_and_datasets_to_locals for this is the only change a
    ported notebook needs. Two things happen beyond the standalone behaviour:

      * Node suffixes are STRIPPED, so single_atom_threshold_Node2 arrives as
        single_atom_threshold and FORT_MM_monitor_Node2 as FORT_MM_monitor.
        Plain names (AllSPCMs_RO1, n_measurements, two_atom_threshold) pass
        through untouched.
      * The submitted arguments from expid are injected. The standalone stack
        archives scan_variable1_name, experiment_function, parent_rid and the
        like AS DATASETS; the master-satellite stack does not, and the plot
        labelling in these notebooks reads them. Without this, a ported cell
        raises NameError partway through for a cosmetic reason.

    Also sets 'node' in the namespace, so a loaded file can say which node it
    came from. Returns the node as well.
    """
    raw = {}
    h5_archive_and_datasets_to_locals(f, raw, quiet=quiet)

    if node is None:
        node = ms_node_of(f)

    resolved = {}
    if node is None:
        resolved.update(raw)
    else:
        tail = "_" + node
        for key, value in raw.items():
            if key.endswith(tail):
                bare = key[: -len(tail)]
                if bare in raw:
                    raise ValueError(
                        f"both {bare!r} and {key!r} are present; stripping "
                        "the suffix would overwrite one with the other"
                    )
                resolved[bare] = value
            else:
                resolved[key] = value

    # Only fill in what the file itself did not record, so a dataset always
    # beats the submitted argument if both exist.
    for key, value in _ms_expid_arguments(f).items():
        resolved.setdefault(key, value)

    resolved["node"] = node
    parent_locals.update(resolved)

    if not quiet:
        print(f"loaded {node or 'un-noded'} run, {len(resolved)} names")
    return node




def h5_archive_and_datasets_to_locals(f, parent_locals, quiet=False):
    """
    Adds the values in archive and datasets fields of an h5 file to your current scope's local variables

    This allows for using the h5's data by name in your code without any additional ceremony.

    Arguments:
        f: the h5 file object
        parent_locals: set this equal to locals() in your code
        quiet: False by default, will print out any fields that failed to be cast to python types. 
            if True, these messages will not be printed.
    Returns:
        nothing is returned
    """
    for data_level in ['archive','datasets']:
        for key in f[data_level].keys():
            try:
                shape = f[data_level][key].shape
                dtype = f[data_level][key].dtype
                raw_value = f[data_level][key][()]
                if shape == (): # scalar
                    if dtype == object:
                        if type(raw_value) == bytes:
                            
                            try:
                                value = str_from_h5(f[data_level][key])
                            except:
                                raise
                        else:
                            try:
                                eval(f[data_level][key][()])
                            except:
                                raise
                    else:
                        value = f[data_level][key][()]
                    # print(key, shape, dtype, value)
                    # locals().update({key: value})
                else:
                    # print(key, shape, dtype, value)
                    value = f[data_level][key][:]
                    # locals().update({key: value})

                if key in ('SPCM0_RO1', 'SPCM0_RO2',
                           'SPCM1_RO1', 'SPCM1_RO2',
                           'AllSPCMs_RO1', 'AllSPCMs_RO2',
                           # AllSPCMs_* is the current name. BothSPCMs_* is
                           # what files written before the rename carry, kept
                           # so old data still gets its leading [0] dataset
                           # seed stripped -- otherwise those arrays come back
                           # off by one, silently.
                           'BothSPCMs_RO1', 'BothSPCMs_RO2'):
                    value = value[1:]
                
                parent_locals.update({key: value})
            except:
                if not quiet:
                    print("oops in:",data_level, key, shape, dtype, value)

def print_h5_archive_and_datasets(f, scalars_only=True, quiet=False):
    """
    Adds the values in archive and datasets fields of an h5 file to your current scope's local variables

    This allows for using the h5's data by name in your code without any additional ceremony.

    Arguments:
        f: the h5 file object
        parent_locals: set this equal to locals() in your code
        quiet: False by default, will print out any fields that failed to be cast to python types. 
            if True, these messages will not be printed.
    Returns:
        nothing is returned
    """
    for data_level in ['archive','datasets']:
        for key in f[data_level].keys():
            try:
                shape = f[data_level][key].shape
                dtype = f[data_level][key].dtype
                raw_value = f[data_level][key][()]
                if shape == (): # scalar
                    if dtype == object:
                        if type(raw_value) == bytes:
                            
                            try:
                                value = str_from_h5(f[data_level][key])
                            except:
                                raise
                        else:
                            try:
                                eval(f[data_level][key][()])
                            except:
                                raise
                    else:
                        value = f[data_level][key][()]
                    # print(key, shape, dtype, value)
                    # locals().update({key: value})
                else:
                    # print(key, shape, dtype, value)
                    value = f[data_level][key][:]
                    # locals().update({key: value})

                if key in ('SPCM0_RO1', 'SPCM0_RO2',
                           'SPCM1_RO1', 'SPCM1_RO2',
                           'AllSPCMs_RO1', 'AllSPCMs_RO2',
                           # AllSPCMs_* is the current name. BothSPCMs_* is
                           # what files written before the rename carry, kept
                           # so old data still gets its leading [0] dataset
                           # seed stripped -- otherwise those arrays come back
                           # off by one, silently.
                           'BothSPCMs_RO1', 'BothSPCMs_RO2'):
                    value = value[1:]

                if scalars_only:
                    try:
                        len(value)
                    except:
                        print(f"{key} = {value}")
                else:
                    print(f"{key} = {value}")
            except:
                if not quiet:
                    print("oops in:",data_level, key, shape, dtype, value)

def get_loading_and_retention(AllSPCMs_RO1, AllSPCMs_RO2, measurements, iterations, cutoff1, cutoff2=None, otsu=False):
        """
        Returns retention, loading rate, and number of atoms loaded for each experiment iteration.
        
        cutoff1 and cutoff2 (optional) are the atom loading thresholds in units counts.

        otsu: if True, will recompute loading using Otsu threshold if initial loading rate calculation > 0.3
        """
        
        if cutoff2 is None:
            cutoff2 = cutoff1
        
        retention_array = np.zeros(iterations)
        loading_rate_array = np.zeros(iterations)
        n_atoms_loaded_array = np.zeros(iterations)
                
        for i in range(iterations):
            shot1 = AllSPCMs_RO1[i*measurements:(i+1)*measurements]
            shot2 = AllSPCMs_RO2[i*measurements:(i+1)*measurements]

            if len(shot1) == 0:
                print(f"iteration {i}, no measurements")
                break
            
            atoms_loaded = [x > cutoff1 for x in shot1] ### results in [true, False] array
            n_atoms_loaded = sum(atoms_loaded)
            loading_fraction = n_atoms_loaded/len(shot1)
            if loading_fraction > 0.3 and otsu:  # apparent very low rate loading might just be wrongly classified background
                cutoff1 = cutoff2 = threshold_otsu(shot1)
                atoms_loaded = [x > cutoff1 for x in shot1]
                n_atoms_loaded = sum(atoms_loaded)
                loading_fraction = n_atoms_loaded / len(shot1)
            
            atoms_retained = [x > cutoff2 and y for x,y in zip(shot2, atoms_loaded)]
            retention_fraction = 0 if not n_atoms_loaded > 0 else sum(atoms_retained)/n_atoms_loaded
            loading_rate_array[i] = n_atoms_loaded/measurements
            n_atoms_loaded_array[i] = n_atoms_loaded
            retention_array[i] = retention_fraction
        return retention_array, loading_rate_array, n_atoms_loaded_array

def compute_cost(retention, loading, cost_function):
    if cost_function == 'atom_blowaway_cost':
        cost = -100*(1-retention)
    elif cost_function == 'atom_retention_cost':
        cost = -100*retention
    elif cost_function == 'atom_loading_with_otsu_threshold_cost' or cost_function == 'atom_loading_cost':
        cost = -100*loading
    else:
        print(f"oops, you need to compute the cost here according to {cost_function}!")
        raise NotImplementedError

# def plot_retention_and_histograms(experiment_name, SPCM0_RO1, SPCM0_RO2, cutoff1,cutoff2,n_measurements, scan_variable1_name, scan_variable2_name, scan_sequence1,scan_sequence2, showloading=False, showhist=True):
#     """
#     Plot retention and readout histogram(s) for a GeneralVariableScan
#     """

#     iterations = len(scan_sequence1)*len(scan_sequence2)
    
#     if scan_variable2_name != '':
#         scan_is_2D = True
#     else:
#         scan_sequence2 = np.zeros(1)
#         scan_is_2D = False

#     retention_array = np.zeros(iterations)
#     loading_rate_array = np.zeros(iterations)
#     n_atoms_loaded_array = np.zeros(iterations)
#     shape = (len(scan_sequence2),len(scan_sequence1))
#     loading_rate_raveled = np.reshape(loading_rate_array,shape,order='F') # rows have constant variable2
#     n_atoms_loaded_raveled = np.reshape(n_atoms_loaded_array,shape,order='F') # rows have constant variable2
#     retention_raveled = np.reshape(retention_array,shape,order='F') # rows have constant variable2
    
#     ncols = len(scan_sequence2)
#     nrows = len(scan_sequence1)
    
#     dvar1 = abs(scan_sequence1[1]-scan_sequence1[0])
#     if scan_is_2D:
#         dvar2 = abs(scan_sequence2[1]-scan_sequence2[0])

#     if showhist:
#         fig,axes = plt.subplots(nrows=nrows,ncols=ncols,figsize=(10,7))
#         for i, ax in enumerate(axes.flat):
#             shot1 = SPCM0_RO1[i*n_measurements:(i+1)*n_measurements]
#             shot2 = SPCM0_RO2[i*n_measurements:(i+1)*n_measurements]
#             ax.hist(shot1,bins=30, facecolor=(0.0, 0.5, 1, 1),label='shot 1')
#             ax.hist(shot2,bins=30, facecolor=(1.0, 0.0, 0.0, 0.1),label='shot 2', edgecolor=(0, 0, 0, 1), linestyle='-')
#             ax.set_title(f"retention={retention_array[i]:.2f}\nloading rate={loading_rate_array[i]:.2f}",fontsize=8)
#             # ax.set_ylabel("occurences")
#             # ax.set_xlabel("photons")
#             ax.set_xticks([])
#             ax.set_yticks([])
#         if scan_is_2D: # todo
#             axes.flat[ncols-1].legend(loc=(1.05,-nrows/2))
#             [axes[-1,ncols-i-1].set_xlabel(var2) for i,var2 in enumerate(scan_sequence2)]
#             [axes[nrows-i-1,0].set_ylabel(var1,rotation=0) for i,var1 in enumerate(scan_sequence1)]
#             [axes[nrows-i-1,0].yaxis.set_label_coords(-0.2,0.4) for i in range(nrows)]
#         fig.text(0.45,-0.5, scan_variable2_name)
#         fig.text(0.05,0.35, scan_variable1_name,rotation=90)
#         plt.subplots_adjust(bottom=-0.4)
#         plt.show()
    
#     if scan_is_2D:
#         # plot a colormap of the retention
#         fig,ax = plt.subplots()
#         cax=ax.imshow(retention_raveled,cmap='afmhot',interpolation='none',
#                       extent=[scan_sequence1[0]-dvar1/2,scan_sequence1[-1]+dvar1/2,scan_sequence2[-1]+dvar2/2,scan_sequence2[0]-dvar2/2])
#         im = ax.get_images()
#         extent =  im[0].get_extent()
#         # plt.setp(ax.spines.values(), linewidth=0.1)
#         ax.set_aspect(abs((extent[1]-extent[0])/(extent[3]-extent[2])))
#         ax.set_xticks(scan_sequence1)
#         ax.set_yticks(scan_sequence2_name)
#         ax.set_title(experiment_name_name)
#         ax.set_xlabel(scan_variable1_name)
#         ax.set_ylabel(scan_variable2_name)
#         # ax.tick_params(axis='both', labelsize=10)
#         fig.colorbar(cax)
#         # plt.clim(0,1)
#         plt.show()

#     # plot a retention curve vs variable 1 for each variable 2 value
#     cmap = mpl.colormaps['inferno']
#     for i, retention, n_loaded, var2 in zip(range(len(scan_sequence2)),retention_raveled, n_atoms_loaded_raveled, scan_sequence2):
#         plt.plot(scan_sequence1, retention,color=cmap(i/len(scan_sequence2)),linestyle='--')
#         plt.scatter(scan_sequence1, retention,color=cmap(i/len(scan_sequence2)),label=scan_variable2_name+"="+str(var2))
#         errs = [1/np.sqrt(n) if n > 0 else np.inf for n in n_loaded]
#         plt.errorbar(scan_sequence1, retention, errs, ls='none',color=cmap(i/len(scan_sequence2)))
#         plt.ylim((0,1))
#         plt.xlabel(scan_variable1_name)
#         plt.ylabel("retention")
#         plt.legend()
#         plt.title(experiment_name)
#         plt.show()
    
#     if showloading:
#         for i, loading, n_loaded, var2 in zip(range(len(scan_sequence2)),loading_rate_raveled, n_atoms_loaded_raveled, scan_sequence2):
#             plt.plot(scan_sequence1, loading,color=cmap(i/len(scan_sequence2)),linestyle='--')
#             plt.scatter(scan_sequence1, loading,color=cmap(i/len(scan_sequence2)),label=scan_variable2_name+"="+str(var2))
#             errs = [1/np.sqrt(n) if n > 0 else np.inf for n in n_loaded]
#             plt.errorbar(scan_sequence1, loading, errs, ls='none',color=cmap(i/len(scan_sequence2)))
#             plt.ylim((0,1))
#             plt.xlabel(scan_variable1_name)
#             plt.ylabel("loading rate")
#             plt.legend()
#             plt.title(experiment_name)
#             plt.show()